Repository arduino/docs-content, pull requests merged in 2022-06, with the labels that each got.

#155 Allow manual deployment
  .github/workflows/deploy-prd.yml
Labels: arduino, infrastructure

#273 [PC-854] Benjamindannegard/max carrier x8 gs
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/x8-getting-started/assets/audio-interface-max-carrier.svg
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/x8-getting-started/assets/connect-x8-to-max-carrier.svg
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/x8-getting-started/assets/lora-on-max-carrier.svg
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/x8-getting-started/content.md
Labels: documentation, Tutorial, arduino, pro

#221 [TC-208] Add GNSS info for Cat M1
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/datasheet/datasheet.md
Labels: documentation, Datasheet, arduino, pro

#290 Updated styleguide link
  CONTRIBUTING.md
Labels: bug, documentation, arduino, maker

#259 Fixed dead link on Introduction to MIDI page
  content/built-in-examples/04.communication/Midi/Midi.md
Labels: fix/update, community

#282 Nano IoT 33 - models added in DS
  content/hardware/03.nano/boards/nano-33-iot/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-33-iot/downloads/ABX00027-datasheet.pdf
Labels: Datasheet, fix/update, arduino, maker

#208 Updated Pin table with D13 info
  content/hardware/03.nano/boards/nano-33-ble/datasheet/datasheet.md
Labels: documentation, Datasheet, arduino, maker

#296 Portenta X8: Add image target version advise[PC-921]
  content/hardware/04.pro/boards/portenta-x8/tutorials/image-flashing/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/out-of-the-box/content.md
Labels: fix/update, Tutorial, arduino, pro

#281 Portenta Breakout render updated
  content/hardware/04.pro/carriers/portenta-breakout/datasheet/assets/breakoutCarrierAssembly.jpg
  content/hardware/04.pro/carriers/portenta-breakout/datasheet/assets/breakoutCarrierShowcase.png
  content/hardware/04.pro/carriers/portenta-breakout/datasheet/assets/breakoutsolution.png
  content/hardware/04.pro/carriers/portenta-breakout/datasheet/assets/featured.png
  content/hardware/04.pro/carriers/portenta-breakout/datasheet/datasheet.md
Labels: Datasheet, fix/update, arduino, pro

#307 Make Grove capital
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/tutorials/smart-garden-project/smart-garden-project.md
Labels: fix/update

#310 updated schematic [MKC-514]
  content/built-in-examples/02.digital/tonePitchFollower/assets/circuit.png
  content/built-in-examples/02.digital/tonePitchFollower/assets/schematic.png
Labels: bug, community, arduino

#287 Add changed send trigger to list of changes in IDE 2.x Serial Monitor
  content/software/ide-v2/tutorials/ide-v2-serial-monitor/ide-v2-serial-monitor.md
Labels: enhancement, arduino

#313 Update memory-guide.md
  content/learn/03.programming/06.memory-guide/memory-guide.md
Labels: documentation, fix/update, community

#295 Make clear that you cannot transmit and receive data at the same time
  content/learn/07.built-in-libraries/04.software-serial/software-serial.md
Labels: fix/update, Tutorial, community

#289 Add library specification to library tutorial
  content/learn/08.contributions/03.arduino-creating-library-guide/arduino-creating-library-guide.md
Labels: enhancement, community

#314 Memory Guide MD Small Update
  content/learn/03.programming/06.memory-guide/memory-guide.md
Labels: documentation, fix/update

#276 Update i2c.md
  content/hardware/03.nano/boards/nano-every/tutorials/i2c/content.md
Labels: fix/update, community, maker

#321 Fix Edge Control Enclosure product pages
  content/hardware/04.pro/carriers/edge-control/compatibility.yml
  content/hardware/04.pro/miscellaneous/enclosure-kit/essentials.md
  content/hardware/04.pro/miscellaneous/enclosure-kit/features.md
Labels: Product page, fix/update, arduino, pro
