Repository arduino/docs-content, pull requests merged in 2022-03, with the labels that each got.

#56 Portenta Breakout - Ozone debugger fix. [PC-865]
  content/hardware/04.pro/carriers/portenta-breakout/tutorials/breakout-jlink-setup/assets/breakout_jlink_optional_settings.png
  content/hardware/04.pro/carriers/portenta-breakout/tutorials/breakout-jlink-setup/breakout-jlink-setup.md
Labels: fix/update, Tutorial

#82 Fixed error in example code
  content/hardware/05.nicla/boards/nicla-sense-me/tutorials/cheat-sheet/cheat-sheet.md
Labels: community

#84 Nicla Vision Proximity tutorial: Update with clearer installing instructions
  content/hardware/05.nicla/boards/nicla-vision/tutorials/proximity/content.md
Labels: fix/update, community

#117 Portenta X8: Datasheet tables fixes
  content/hardware/04.pro/boards/portenta-x8/datasheet/datasheet.md
Labels: Datasheet, fix/update

#122 Jhansson ard/schematic update [MKC-381]
  content/built-in-examples/09.usb/ButtonMouseControl/ButtonMouseControl.md
  content/built-in-examples/09.usb/ButtonMouseControl/assets/schematic.png
Labels: fix/update, Tutorial, arduino

#125 Link updated
  content/hacking/01.software/LibraryTutorial/LibraryTutorial.md
Labels: fix/update, community

#93 CAT M1 datasheet fixes
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/datasheet/assets/thalesPinout.svg
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/datasheet/datasheet.md
Labels: fix/update, Tutorial, arduino
