Repository arduino/docs-content, pull requests merged in 2022-11, with the labels that each got.

#621 Fix Serial Plotter sketches for compatibility with all IDE versions
  content/software/ide-v2/tutorials/ide-v2-serial-plotter/ide-v2-serial-plotter.md
Labels: arduino

#620 Linter: USB-C trademark miss-spelling rule and content fix [PC-1014, PC-1015]
  content/hardware/02.hero/boards/uno-mini-le/datasheet/datasheet.md
  content/hardware/02.hero/boards/uno-mini-le/features.md
  content/hardware/02.hero/boards/uno-mini-le/product.md
  content/hardware/02.hero/boards/uno-mini-le/tutorials/uno-mini-le-guide/uno-mini-le-guide.md
  content/hardware/03.nano/carriers/nano-motor-carrier/tutorials/nano-matlab-wifi-led/nanoMatlabWiFiLED.md
  content/hardware/04.pro/boards/portenta-h7/datasheets/datasheet.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/ble-connectivity/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/creating-gui-with-lvgl/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/dual-core-processing/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/flash-optimized-key-value-store/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/getting-started-openmv-micropython/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/over-the-air-update/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/reading-writing-flash-memory/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/setting-up-portenta/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/usb-host/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/wifi-access-point/content.md
  content/hardware/04.pro/boards/portenta-x8/datasheet/datasheet.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/custom-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/datalogging-iot/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/display-output-webgl/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/docker-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/image-flashing/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/multi-protocol-gateway/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/waves-fleet-managment/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/wordpress-webserver/content.md
  content/hardware/04.pro/carriers/portenta-breakout/datasheet/datasheet.md
  content/hardware/04.pro/carriers/portenta-breakout/tutorials/getting-started/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/catm1-and-nbiot/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/connecting-to-ttn/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/getting-started/content.md
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/tutorials/getting-started/getting-started.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/blob-detection/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/camera-to-bitmap-sd-card/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/custom-machine-learning-model/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/ethernet-with-ide/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/ethernet-with-openmv/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/getting-started-camera/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/things-network-openmv/content.md
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/connecting-to-iot-cloud/content.md
  content/hardware/07.edu/carriers/braccio-carrier/datasheet/datasheet.md
  content/hardware/_unlisted/old-datasheets/portenta-h7-full/datasheet.md
  content/hardware/_unlisted/old-datasheets/portenta-h7-lite-connected/datasheet.md
  content/hardware/_unlisted/old-datasheets/portenta-h7-lite/datasheet.md
  content/learn/04.electronics/06.power-tree/power-tree-style-guide.md
  scripts/validation/rules/rules-trademarks.yml
Labels: fix/update, arduino

#624 Nicla Sense ME WebBLE Sketch: Fix device name [PC-1008]
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/web-ble-dashboard/content.md
Labels: fix/update, Tutorial, arduino, pro

#634 Opta WiFi: Fix naming
  content/hardware/05.pro-solutions/solutions-and-kits/opta/features.md
  content/hardware/05.pro-solutions/solutions-and-kits/opta/tech-specs.yml
Labels: Product page, fix/update, arduino, pro

#636 Add Opta WiFi RS485 support in tech specs table
  content/hardware/05.pro-solutions/solutions-and-kits/opta/tech-specs.yml
Labels: documentation, fix/update, arduino

#632 Linter: USB-C trademark regex fix [PC-1014]
  content/hardware/02.hero/boards/uno-mini-le/datasheet/datasheet.md
  content/hardware/02.hero/boards/uno-mini-le/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7-lite-connected/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7-lite/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7/tutorials/ble-connectivity/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/dual-core-processing/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/flash-optimized-key-value-store/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/lauterbach-debugger/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/setting-up-portenta/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/updating-the-bootloader/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/usb-host/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/wifi-access-point/content.md
  content/hardware/04.pro/boards/portenta-x8/tech-specs.yml
  content/hardware/04.pro/boards/portenta-x8/tutorials/uploading-sketches-m4/content.md
  content/hardware/04.pro/carriers/portenta-breakout/tutorials/getting-started/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/datasheet/datasheet.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/blob-detection/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/camera-to-bitmap-sd-card/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/connecting-to-ttn/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/creating-basic-face-filter/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/getting-started-camera/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/datasheet/datasheet.md
  content/hardware/05.pro-solutions/solutions-and-kits/wisgate-edge-lite-2/tech-specs.yml
  content/hardware/05.pro-solutions/solutions-and-kits/wisgate-edge-pro/tech-specs.yml
  content/hardware/06.nicla/boards/nicla-vision/tutorials/blob-detection/content.md
  content/hardware/06.nicla/boards/nicla-vision/tutorials/getting-started/content.md
  content/hardware/07.edu/carriers/braccio-carrier/tech-specs.yml
  content/hardware/08.kits/maker/make-your-uno-kit/features.md
  content/hardware/08.kits/maker/make-your-uno-kit/tech-specs.yml
  scripts/validation/rules/rules-trademarks.yml
Labels: fix/update, arduino, infrastructure

#657 Linter: Add Edge Impulse® trademark rule[PC-1037]
  content/hardware/03.nano/boards/nano-33-ble-sense/tutorials/edge-impulse/edge-impulse.md
  content/hardware/03.nano/boards/nano-rp2040-connect/features.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/custom-machine-learning-model/content.md
  content/hardware/06.nicla/boards/nicla-vision/tutorials/image-classification/content.md
  scripts/validation/rules/rules-trademarks.yml
Labels: fix/update, arduino, infrastructure

#667 Fix Pro solutions HW compatibiltiy links
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/compatibility.yml
  content/hardware/05.pro-solutions/solutions-and-kits/enclosure-kit/tutorials/assembly-instructions/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/wisgate-edge-lite-2/tutorials/getting-started/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/wisgate-edge-pro/tutorials/pole-mounting/content.md
Labels: Product page, fix/update, Tutorial, arduino

#119 Add information on how to change the start address
  content/hardware/04.pro/boards/portenta-h7/tutorials/updating-the-bootloader/content.md
Labels: fix/update, Tutorial, arduino

#629 Remove "Board Recovery" section from datasheets of boards without feature
  content/hardware/02.hero/boards/mega-2560/datasheet/datasheet.md
  content/hardware/02.hero/boards/uno-mini-le/datasheet/datasheet.md
  content/hardware/02.hero/boards/uno-rev3/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-every/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano/datasheet/datasheet.md
  content/hardware/08.kits/maker/make-your-uno-kit/datasheet/datasheet.md
Labels: bug, Datasheet, arduino

#680 Datasheet renderer new integration: Fix and update npm package info [PC-999]
  scripts/datasheet-rendering/package-lock.json
  scripts/datasheet-rendering/package.json
Labels: fix/update, arduino, infrastructure

#693 Downloads: Fix schematics PDF naming
  content/hardware/01.mkr/01.boards/mkr-1000-wifi/downloads/ABX00004-schematics.pdf
  content/hardware/01.mkr/01.boards/mkr-fox-1200/downloads/ABX00014-schematics.pdf
  content/hardware/01.mkr/01.boards/mkr-gsm-1400/downloads/ABX00018-schematics.pdf
  content/hardware/01.mkr/01.boards/mkr-nb-1500/downloads/ABX00019-schematics.pdf
  content/hardware/03.nano/boards/nano-33-ble-sense/downloads/ABX00031-schematics.pdf
  content/hardware/03.nano/boards/nano-33-ble/downloads/ABX00030-schematics.pdf
  content/hardware/03.nano/boards/nano/downloads/A000005-schematics.pdf
Labels: Product page, fix/update, arduino, maker

#623 Scripts: Content-linter fix
  .vscode/tasks.json
  scripts/spell-check-fix.cmd
  scripts/validation/fix-issues.js
  scripts/validation/package-lock.json
  scripts/validation/package.json
Labels: fix/update, arduino, infrastructure
