Repository arduino/docs-content, pull requests merged in 2023-04, with the labels that each got.

#895 [AE-13] Arduino Agent -> Arduino Create Agent
  content/arduino-cloud/01.getting-started/01.iot-cloud-getting-started/iot-cloud-getting-started.md
Labels: fix/update

#978 [AE-63] Arduino IDE pre-requisites in Linux
  content/software/ide-v2/tutorials/getting-started/01.ide-v2-downloading-and-installing/ide-v2-downloading-and-installing.md
Labels: bug, documentation, fix/update, arduino

#997 [PC-1217] - Opta Pinouts Documents
  content/hardware/07.opta/opta-family/opta/downloads/opta-full-pinout.pdf
Labels: documentation, Product page, arduino, pro

#893 Update security-considerations.md
  content/arduino-cloud/02.features/00.security-considerations/security-considerations.md
Labels: arduino

#858 Fix `contributeURL` parameter
  content/tutorials/generic/micropython-installation/micropython-installation.md
Labels: fix/update, arduino

#849 Add begin() function to class example as best practice
  content/learn/08.contributions/03.arduino-creating-library-guide/arduino-creating-library-guide.md
Labels: bug, community, maker

#1013 Update IDE nomenclature
  content/arduino-cloud/01.getting-started/07.arduino-cloud-cli/arduino-cloud-cli.md
  content/arduino-cloud/02.features/05.sharing-dashboards/sharing-dashboards.md
  content/arduino-cloud/02.features/07.nodered/nodered-intro.md
  content/arduino-cloud/03.tutorials/cloud-environmental-data/cloud-environmental-data.md
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/atmel-ice/using-an-atmel-ice-with-the-ide-v2.md
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-jlink-setup/mkr-jlink.md
  content/hardware/02.hero/boards/uno-mini-le/tutorials/uno-mini-le-guide/uno-mini-le-guide.md
  content/hardware/02.hero/boards/zero/features.md
  content/hardware/02.hero/boards/zero/tutorials/debugging-with-zero/debugging-with-zero.md
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/tutorials/cheat-sheet/ble-cheat-sheet.md
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/tutorials/humidity-and-temperature-sensor/content.md
  content/hardware/03.nano/boards/nano-33-ble-sense/tutorials/cheat-sheet/ble-cheat-sheet.md
  content/hardware/03.nano/boards/nano-rp2040-connect/tutorials/rp2040-01-technical-reference/rp2040-01-technical-reference.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/secure-boot/secure-boot.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/03.uploading-sketches-m4/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/04.python-arduino-data-exchange/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/05.docker-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/07.custom-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/10.datalogging-iot/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/12.multi-protocol-gateway/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/getting-started/content.md
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/speech-recognition-engine/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/tutorials/plc-ide-setup-license/content.md
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/ei-intruder-detector/content.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/getting-started-ml/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/getting-started-connectivity/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/getting-started-with-modbus-rtu/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/getting-started-with-rs485/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/getting-started/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/getting-started/mac-address/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/memory-partitioning/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/tank-level-app-note/content.md
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-getting-started/giga-getting-started.md
  content/learn/01.starting-guide/00.getting-started-arduino/getting-started-arduino.md
  content/learn/02.microcontrollers/04.debugging/debugging.md
  content/software/ide-v2/tutorials/01.getting-started-ide-v2/ide-v2-autocomplete-feature.md
  content/software/ide-v2/tutorials/getting-started/01.ide-v2-downloading-and-installing/ide-v2-downloading-and-installing.md
  content/software/ide-v2/tutorials/getting-started/02.ide-v2-uploading-a-sketch/ide-v2-uploading-a-sketch.md
  content/software/ide-v2/tutorials/ide-v2-autocomplete-feature/ide-v2-autocomplete-feature.md
  content/software/ide-v2/tutorials/ide-v2-board-manager/ide-v2-board-manager.md
  content/software/ide-v2/tutorials/ide-v2-cloud-sketch-sync/ide-v2-cloud-sketch-sync.md
  content/software/ide-v2/tutorials/ide-v2-customize-auto-formatter/content.md
  content/software/ide-v2/tutorials/ide-v2-debugger/ide-v2-debugger.md
  content/software/ide-v2/tutorials/ide-v2-installing-a-library/ide-v2-installing-a-library.md
  content/software/ide-v2/tutorials/ide-v2-serial-monitor/ide-v2-serial-monitor.md
  content/software/ide-v2/tutorials/ide-v2-serial-plotter/ide-v2-serial-plotter.md
  content/tutorials/generic/amplitude-serial-plotter/amplitude-serial-plotter.md
Labels: fix/update, arduino

#947 [PC-1182] Portenta X8: User Manual OS Image Section Update
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/assets/breakout-dip-switches.png
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/assets/max-carrier-dip-switches.png
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/assets/uuu-flashing-success.png
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
Labels: documentation, enhancement, fix/update, arduino, pro
