Repository arduino/docs-content, pull requests merged in 2023-11, with the labels that each got.

#1420 [MKC-1240]Rework I2C article
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/qwiic/qwiic.md
  content/learn/05.communication/01.wire/assets/AD5171_bb.png
  content/learn/05.communication/01.wire/assets/AD5171_pinconfig.png
  content/learn/05.communication/01.wire/assets/AD5171_sch.png
  content/learn/05.communication/01.wire/assets/GroveIMU.png
  content/learn/05.communication/01.wire/assets/GroveOLED.png
  content/learn/05.communication/01.wire/assets/I2C.png
  content/learn/05.communication/01.wire/assets/I2Cb2b.png
  content/learn/05.communication/01.wire/assets/Qwiic-bmp280.png
  content/learn/05.communication/01.wire/assets/Qwiic.png
  content/learn/05.communication/01.wire/assets/SRF_sch.png
  content/learn/05.communication/01.wire/assets/SRFxx_bb.png
  content/learn/05.communication/01.wire/assets/uno-i2c.png
  content/learn/05.communication/01.wire/assets/wifi-1010-i2c.png
  content/learn/05.communication/01.wire/assets/wiring.png
  content/learn/05.communication/01.wire/wire.md
Labels: documentation, arduino, maker

#1453 [MKC-1208] UART Learn Article
  content/learn/05.communication/09.uart/assets/circuit.png
  content/learn/05.communication/09.uart/assets/dataBits.png
  content/learn/05.communication/09.uart/assets/message.png
  content/learn/05.communication/09.uart/assets/parallelSerial.png
  content/learn/05.communication/09.uart/assets/parityBit.png
  content/learn/05.communication/09.uart/assets/startBit.png
  content/learn/05.communication/09.uart/assets/stopBits.png
  content/learn/05.communication/09.uart/uart.md
Labels: documentation, arduino, maker

#1458 UNO R4 WiFi firmware Help Center article Links in Cheat Sheet
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: fix/update, arduino, maker

#1451 [HWU4M-71] Add BLE example
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: documentation, arduino, maker

#1426 Fix: In MKR Relay Shield `AREF` and `A0` are mistakenly noted as `SDA` and `SCL` respectively.
  content/hardware/01.mkr/02.shields/mkr-485-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-can-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-env-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-eth-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-gps-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-imu-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-mem-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-relay-proto-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-rgb-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-sd-proto-shield/interactive/pinout.png
  content/hardware/01.mkr/02.shields/mkr-therm-shield/interactive/pinout.png
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/interactive/pinout.png
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/interactive/pinout.png
  content/hardware/01.mkr/03.carriers/mkr-motor-carrier/interactive/pinout.png
Labels: documentation, arduino, maker

#1456 [PC-1448] - Portenta C33/H7 Tech Specs Table Update
  content/hardware/04.pro/boards/portenta-c33/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7-lite-connected/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7-lite/tech-specs.yml
  content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
Labels: fix/update, arduino, pro

#1467 [MKC-1260] SPIFFS Docs Nano ESP32
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/burnBootloader.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/openExample.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/selectBoard.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/selectProgrammer.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/selectSPIFFS.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/serialOutput.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/twoPorts.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/assets/uploadProgrammer.png
  content/hardware/03.nano/boards/nano-esp32/tutorials/spiff/spiff.md
Labels: documentation, arduino, maker

#1495 [PC-1164] Portenta Max Carrier Antennas Added to Datasheet
  content/hardware/04.pro/carriers/portenta-max-carrier/datasheet/datasheet.md
Labels: fix/update, arduino, pro

#1504 [Giga Display Shield] Datasheet Update
  content/hardware/10.mega/shields/giga-display-shield/datasheet/datasheet.md
Labels: fix/update, arduino, maker

#1493 Update esp32-upload.md
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/esp32-upload/esp32-upload.md
Labels: documentation, arduino, maker

#1508 Correct CVD links
  content/arduino-cloud/09.business/00.security-considerations/security-considerations.md
  content/software/ide-v1/tutorials/ide-v1-security/ide-v1-security.md
  content/software/ide-v2/tutorials/ide-v2-security/ide-v2-security.md
Labels: bug, arduino

#1455 Fix typo StringReplace.md
  content/built-in-examples/08.strings/StringReplace/StringReplace.md
Labels: fix/update, community

#1526 Portenta Hat Carrier: User Manual Content Patch
  content/hardware/04.pro/carriers/portenta-hat-carrier/tutorials/user-manual/content.md
Labels: Tutorial, arduino, pro

#1520 [GIGA R1] Dual Core Article fixes
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-dual-core/giga-dual-core.md
Labels: fix/update, arduino, maker
