Repository arduino/docs-content, pull requests merged in 2023-01, with the labels that each got.

#752 [TC-416] Fix resistor values in make your Uno kit
  content/hardware/08.kits/maker/make-your-uno-kit/datasheet/datasheet.md
Labels: Datasheet, fix/update

#758 [TC-406] Small change to mention of Type-C connector in X8 DS
  content/hardware/04.pro/boards/portenta-x8/datasheet/datasheet.md
Labels: Datasheet, fix/update

#775 [TC-424] Update Pinout image in MKR IoT Carrier Rev2 DS (2nd Attempt)
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/datasheet/assets/Pinout.png
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/datasheet/datasheet.md
Labels: Datasheet, fix/update

#782 [PC-1071] Arduino Opta: Certification inconsistencies fix
  content/hardware/05.pro-solutions/solutions-and-kits/opta/product.md
Labels: fix/update, arduino

#791 Update mkr-iot-carrier-02-technical-reference.md-MKC-805
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/tutorials/cheat-sheet/assets/apds-9960.png
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/tutorials/cheat-sheet/cheat-sheet.md
Labels: documentation, fix/update, arduino

#790 Update mkr-iot-carrier-01-technical-reference.md-MKC-805
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/tutorials/mkr-iot-carrier-01-technical-reference/mkr-iot-carrier-01-technical-reference.md
Labels: documentation, fix/update, arduino

#770 Fix Gyroscope spelling
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/datasheet/datasheet.md
Labels: Datasheet, fix/update

#802 Trademark changes on Product page
  content/hardware/05.pro-solutions/solutions-and-kits/opta/features.md
  content/hardware/05.pro-solutions/solutions-and-kits/opta/product.md
  content/hardware/05.pro-solutions/solutions-and-kits/opta/tech-specs.md
  content/hardware/05.pro-solutions/solutions-and-kits/opta/tech-specs.yml
Labels: Product page, fix/update, arduino

#796 Adding Feature buttons for Hero Shields- MKC-769
  content/hardware/02.hero/shields/4-relays-shield/features.md
  content/hardware/02.hero/shields/9-axis-motion-shield/features.md
  content/hardware/02.hero/shields/ethernet-shield-rev2/features.md
  content/hardware/02.hero/shields/motor-shield-rev3/features.md
Labels: enhancement

#795 Adding Feature buttons for Hero Boards - MKC-768
  content/hardware/02.hero/boards/due/features.md
  content/hardware/02.hero/boards/leonardo/features.md
  content/hardware/02.hero/boards/mega-2560/features.md
  content/hardware/02.hero/boards/micro/features.md
  content/hardware/02.hero/boards/uno-mini-le/features.md
  content/hardware/02.hero/boards/uno-rev3-smd/features.md
  content/hardware/02.hero/boards/uno-rev3/features.md
  content/hardware/02.hero/boards/uno-wifi-rev2/features.md
  content/hardware/02.hero/boards/yun-rev2/features.md
  content/hardware/02.hero/boards/zero/features.md
Labels: enhancement, Product page

#794 Adding Feature buttons for Nano Carriers - MKC-766
  content/hardware/03.nano/carriers/nano-motor-carrier/features.md
  content/hardware/03.nano/carriers/nano-screw-terminal-adapter/features.md
Labels: enhancement

#793 Adding Feature buttons for MKR Shields- MKC-770
  content/hardware/01.mkr/03.carriers/mkr-connector-carrier/features.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/features.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/features.md
  content/hardware/01.mkr/03.carriers/mkr-motor-carrier/features.md
Labels: enhancement

#788 Update link to Ethernet library
  content/hardware/01.mkr/02.shields/mkr-eth-shield/tutorials/mkr-eth-shield-webserver/mkr-eth-shield-webserver.md
Labels: fix/update, arduino

#789 Adding Feature buttons for MKR Shields- MKC-767
  content/hardware/01.mkr/02.shields/mkr-485-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-can-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-env-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-eth-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-gps-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-imu-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-mem-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-relay-proto-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-rgb-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-sd-proto-shield/features.md
  content/hardware/01.mkr/02.shields/mkr-therm-shield/features.md
Labels: enhancement

#787 Hannes7eicher/nano 33 ble sense rev2 feature buttons
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/features.md
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/tutorials/imu-accelerometer/content.md
Labels: enhancement
