Repository arduino/docs-content, pull requests merged in 2023-07, with the labels that each got.

#1116 [PC-1265] Quickstart URL updated
  content/hardware/04.pro/boards/portenta-h7-lite-connected/essentials.md
  content/hardware/04.pro/boards/portenta-h7-lite-connected/product.md
  content/hardware/04.pro/boards/portenta-h7-lite/essentials.md
  content/hardware/04.pro/boards/portenta-h7-lite/product.md
  content/hardware/04.pro/boards/portenta-h7/essentials.md
  content/hardware/04.pro/boards/portenta-h7/product.md
  content/hardware/04.pro/carriers/portenta-breakout/essentials.md
  content/hardware/04.pro/carriers/portenta-max-carrier/product.md
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/essentials.md
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/product.md
  content/hardware/04.pro/shields/portenta-vision-shield/essentials.md
  content/hardware/04.pro/shields/portenta-vision-shield/product.md
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/essentials.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/essentials.md
  content/hardware/06.nicla/boards/nicla-vision/product.md
  content/hardware/06.nicla/boards/nicla-voice/essentials.md
Labels: fix/update, arduino

#1155 Update cheat-sheet.md Changed typo of ADC to DAC
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/cheat-sheet/cheat-sheet.md
Labels: bug, community

#1170 Update ide-v2-cloud-sketch-sync.md
  content/software/ide-v2/tutorials/ide-v2-cloud-sketch-sync/ide-v2-cloud-sketch-sync.md
Labels: fix/update, community, maker

#1160 User manual improvement, note as a new subsection
  content/hardware/06.nicla/boards/nicla-voice/tutorials/user-manual/content.md
Labels: enhancement, arduino, pro

#1145 [MKC-1015]Fix range of PWM pins
  content/hardware/10.mega/boards/giga-r1-wifi/datasheet/datasheet.md
  content/hardware/10.mega/boards/giga-r1-wifi/downloads/ABX00063-full-pinout.pdf
  content/hardware/10.mega/boards/giga-r1-wifi/downloads/ABX00063-pinout.png
  content/hardware/10.mega/boards/giga-r1-wifi/interactive/ABX00063-pinout.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: Datasheet, fix/update, arduino

#1179 Update eeprom-guide.md
  content/learn/03.programming/07.eeprom-guide/eeprom-guide.md
Labels: community

#1178 Fixed missing semicolon.
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: community

#1177 Update eeprom.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/eeprom/eeprom.md
Labels: community

#1176 Added some stuff to EEPROM section
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/cheat-sheet/cheat-sheet.md
Labels: community

#1114 Breakline fix on mechanical information. Grammar re-check
  content/hardware/02.hero/boards/uno-r4-wifi/datasheet/datasheet.md
Labels: bug, arduino

#1050 [PC-1135] Legal updates
  content/hardware/07.opta/opta-family/opta/datasheet/datasheet.md
Labels: arduino, pro

#1139 [MKC-1011] [UNO R4 WiFi] VRTC & Off Pin tutorial
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/vrtc-off/assets/Circuit.png
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/vrtc-off/assets/OFF.png
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/vrtc-off/assets/headers.png
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/vrtc-off/vrtc-off.md
Labels: Tutorial, arduino

#1203 [MKC-1061]MicroPython 101 revision
  content/micropython-course/course/00.introduction-arduino/intro-to-arduino.md
  content/micropython-course/course/01.introduction-python/02.intro-to-micropython.md
  content/micropython-course/course/01.introduction-python/assets/boot.png
  content/micropython-course/course/01.introduction-python/assets/download.png
  content/micropython-course/course/01.introduction-python/assets/libFolderIn.png
  content/micropython-course/course/01.introduction-python/assets/main.png
  content/micropython-course/course/01.introduction-python/assets/wifiConnected.png
  content/micropython-course/course/02.installation/assets/bootloader.png
  content/micropython-course/course/02.installation/installation-tools.md
  content/micropython-course/course/03.python-cc/python-cc.md
  content/micropython-course/course/04.digital/03.digital.md
  content/micropython-course/course/05.analog/04.analog.md
  content/micropython-course/course/06.serial/05.serial-protocols.md
  content/micropython-course/course/06.serial/assets/spi.png
  content/micropython-course/course/07.internet-of-things/01.internet-of-things.md
  content/micropython-course/course/08.examples/examples.md
  content/micropython-course/projects/alarm-clock/alarm-clock-project.md
  content/micropython-course/projects/scene-changer/scene-changer.md
  content/micropython-course/projects/temperature-display/temperature-display-project.md
Labels: arduino, maker

#1233 Correct pin numbers for Nano ESP32 LED
  content/hardware/03.nano/boards/nano-esp32/tutorials/cheat-sheet/cheat-sheet.md
Labels: bug, arduino
