Repository arduino/docs-content, pull requests merged in 2023-02, with the labels that each got.

#810 Update Portenta H7 power consumption
  content/hardware/04.pro/boards/portenta-h7/datasheets/datasheet.md
Labels: Datasheet, fix/update

#809 Add Nicla Vision power consumption
  content/hardware/06.nicla/boards/nicla-vision/datasheet/datasheet.md
Labels: Datasheet, fix/update

#784 Hannes7eicher/nano feature buttons mkc 765
  content/hardware/03.nano/boards/nano-33-ble-sense/features.md
  content/hardware/03.nano/boards/nano-33-ble/features.md
  content/hardware/03.nano/boards/nano-33-iot/features.md
  content/hardware/03.nano/boards/nano-every/features.md
  content/hardware/03.nano/boards/nano-rp2040-connect/features.md
  content/hardware/03.nano/boards/nano/features.md
Labels: enhancement

#823 Revert docs version to `v1.7.83`
  package-lock.json
  package.json
Labels: fix/update, arduino, infrastructure

#786 Adding Feature buttons for MKR Boards - MKC-764
  content/hardware/01.mkr/01.boards/mkr-1000-wifi/features.md
  content/hardware/01.mkr/01.boards/mkr-fox-1200/features.md
  content/hardware/01.mkr/01.boards/mkr-gsm-1400/features.md
  content/hardware/01.mkr/01.boards/mkr-nb-1500/features.md
  content/hardware/01.mkr/01.boards/mkr-vidor-4000/features.md
  content/hardware/01.mkr/01.boards/mkr-wan-1300/features.md
  content/hardware/01.mkr/01.boards/mkr-wan-1310/features.md
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/features.md
  content/hardware/01.mkr/01.boards/mkr-zero/features.md
Labels: enhancement

#806 [TC-439] Explain open-source firmware of the M7 core in X8 Datasheet
  content/hardware/04.pro/boards/portenta-x8/datasheet/datasheet.md
Labels: Datasheet, fix/update, community

#641 Linter: Add NXP® trademark rule [PC-1024]
  content/hardware/01.mkr/02.shields/mkr-can-shield/tech-specs.yml
  content/hardware/04.pro/boards/portenta-x8/features.md
  content/hardware/04.pro/boards/portenta-x8/tech-specs.yml
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/datasheet/datasheet.md
  content/hardware/06.nicla/boards/nicla-vision/datasheet/datasheet.md
  content/hardware/06.nicla/boards/nicla-vision/tech-specs.yml
  content/hardware/_unlisted/old-datasheets/portenta-h7-full/datasheet.md
  content/hardware/_unlisted/old-datasheets/portenta-h7-lite-connected/datasheet.md
  content/hardware/_unlisted/old-datasheets/portenta-h7-lite/datasheet.md
  content/retired/02.shields/arduino-lucky-shield/content.md
Labels: fix/update, arduino, infrastructure

#827 Fix broken URLs and links
  content/built-in-examples/02.digital/toneMelody/toneMelody.md
  content/built-in-examples/02.digital/toneMultiple/toneMultiple.md
  content/built-in-examples/02.digital/tonePitchFollower/tonePitchFollower.md
  content/built-in-examples/03.analog/AnalogInOutSerial/AnalogInOutSerial.md
  content/built-in-examples/03.analog/AnalogWriteMega/AnalogWriteMega.md
  content/built-in-examples/03.analog/Fading/Fading.md
  content/built-in-examples/04.communication/Dimmer/Dimmer.md
  content/built-in-examples/04.communication/PhysicalPixel/PhysicalPixel.md
  content/built-in-examples/04.communication/SerialCallResponse/SerialCallResponse.md
  content/built-in-examples/04.communication/VirtualColorMixer/VirtualColorMixer.md
  content/built-in-examples/05.control-structures/Arrays/Arrays.md
  content/built-in-examples/05.control-structures/SwitchCase2/SwitchCase2.md
  content/built-in-examples/05.control-structures/WhileStatementConditional/WhileStatementConditional.md
  content/built-in-examples/06.sensors/ADXL3xx/ADXL3xx.md
  content/built-in-examples/06.sensors/Memsic2125/Memsic2125.md
  content/built-in-examples/08.strings/CharacterAnalysis/CharacterAnalysis.md
  content/built-in-examples/08.strings/StringAdditionOperator/StringAdditionOperator.md
  content/built-in-examples/08.strings/StringLength/StringLength.md
  content/built-in-examples/08.strings/StringLengthTrim/StringLengthTrim.md
  content/built-in-examples/08.strings/StringStartsWithEndsWith/StringStartsWithEndsWith.md
  content/built-in-examples/09.usb/ButtonMouseControl/ButtonMouseControl.md
  content/built-in-examples/09.usb/KeyboardLogout/KeyboardLogout.md
  content/built-in-examples/09.usb/KeyboardReprogram/KeyboardReprogram.md
  content/built-in-examples/09.usb/KeyboardSerial/KeyboardSerial.md
  content/hardware/01.mkr/01.boards/mkr-1000-wifi/tutorials/analog-to-midi/AnalogToMidi.md
  content/hardware/02.hero/boards/zero/tutorials/simple-audio-frequency-meter/simple-audio-frequency-meter.md
  content/learn/04.electronics/03.lcd-displays/lcd-displays.md
  content/learn/04.electronics/09.transistor-motor-control/09.transistor-motor-control.md
  content/library-examples/esplora-library/EsploraJoystickMouse/EsploraJoystickMouse.md
  content/library-examples/wifi-library/WiFiRTC/WiFiRTC.md
  content/library-examples/wifi-library/WiFiWebClientRepeating/WiFiWebClientRepeating.md
  content/retired/06.getting-started-guides/IntelGalileoGen2/IntelGalileoGen2.md
  content/tutorials/communication/wifi-nina-examples/wifi-nina-examples.md
  content/tutorials/generic/WiFi101ThingSpeakDataUploader/WiFi101ThingSpeakDataUploader.md
  content/tutorials/generic/Wifi101GoogleCalendar/Wifi101GoogleCalendar.md
  content/tutorials/generic/digital-input-pullup/digital-input-pullup.md
  content/tutorials/generic/scheduled-wifi-ssl-web-client/scheduled-wifi-ssl-web-client.md
  content/tutorials/generic/simple-rtc-alarm/simple-rtc-alarm.md
  content/tutorials/generic/simple-rtc/simple-rtc.md
  content/tutorials/generic/sleep-rtc-alarm/sleep-rtc-alarm.md
Labels: bug, arduino

#828 Hannes7eicher/Plant-Watering-Kit-Asset-Update [MKC-828]
  content/hardware/08.kits/maker/plant-watering-kit/image.svg
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/Dashboard.gif
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/Things.jpg
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/dashboard-overview.jpg
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/dashboard-overview.png
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/dashboard_initial.png
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/template_overview.png
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/assets/things.png
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/content.md
Labels: enhancement, arduino

#485 [TC-346] MKR WiFi 1010 App Note
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/battery-in-mkr.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/calculation-serial-printing.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/configuration-code.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/include-BQ24195-library.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/lipo-battery-breakdown.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/lipo-battery-multimeter.jpg
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/lipo-vcc-multimeter.jpg
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/maxCurrentDraw.svg
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/serial-BQ24195-setup.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/three-lipo-batteries.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/voltage-divider-samd21.png
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/assets/vout.svg
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-battery-app-note/mkr-battery-app-note.md
Labels: documentation, Tutorial

#837 Fix wrong link to RP2040 IMU
  content/hardware/03.nano/boards/nano-rp2040-connect/features.md
Labels: fix/update, arduino

#843 Hannes7eicher/Fix broken Nano 33 BLE Sense Rev2 [MKC-844]
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/tutorials/humidity-and-temperature-sensor/content.md
Labels: fix/update, arduino

#851 Add template section for IoT Bundle projects [MKC-827]
  content/hardware/08.kits/maker/iot-bundle/tutorials/i-love-you-pillow/assets/template_overview.png
  content/hardware/08.kits/maker/iot-bundle/tutorials/i-love-you-pillow/content.md
  content/hardware/08.kits/maker/iot-bundle/tutorials/pavlovs-cat/assets/template_overview.png
  content/hardware/08.kits/maker/iot-bundle/tutorials/pavlovs-cat/content.md
  content/hardware/08.kits/maker/iot-bundle/tutorials/plant-communicator/assets/template_overview.png
  content/hardware/08.kits/maker/iot-bundle/tutorials/plant-communicator/content.md
  content/hardware/08.kits/maker/iot-bundle/tutorials/puzzlebox/assets/template_overview.png
  content/hardware/08.kits/maker/iot-bundle/tutorials/puzzlebox/content.md
  content/hardware/08.kits/maker/iot-bundle/tutorials/the-nerd/assets/template_overview.png
  content/hardware/08.kits/maker/iot-bundle/tutorials/the-nerd/content.md
Labels: documentation, arduino

#852 [PC-1117] Arduino Opta: Opta compatibility update for Arduino and Modbus article
  content/learn/05.communication/07.modbus/modbus.md
Labels: fix/update, arduino

#859 Plant Watering Kit Content Revision
  content/hardware/08.kits/maker/plant-watering-kit/tutorials/iot-smart-garden-setup-with-nanorp2040/content.md
Labels: documentation, arduino

#861 Portenta X8 tutorial: Fix code block
  content/hardware/04.pro/boards/portenta-x8/tutorials/multi-protocol-gateway/content.md
Labels: fix/update, Tutorial, community, pro
