Repository arduino/docs-content, pull requests merged in 2024-05, with the labels that each got.

#1762 Update content.md
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
Labels: fix/update, arduino, pro

#1911 Validation Rules updates
  scripts/validation/rules/rules-trademarks.yml
  scripts/validation/rules/rules-tutorials.yml
Labels: arduino, infrastructure

#1897 Updating trademarks in mkr datasheets
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/datasheet/datasheet.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/datasheet/datasheet.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/datasheet/datasheet.md
Labels: documentation, Datasheet, arduino, maker

#1898 Updating trademarks for Nano products
  content/hardware/03.nano/boards/nano-33-ble-rev2/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-33-ble-sense/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-33-ble/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-33-iot/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-esp32/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-every/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-rp2040-connect/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano/datasheet/datasheet.md
Labels: documentation, Datasheet, arduino, maker

#1887 Replace links to ephemeral file URLs with relative paths
  content/hardware/03.nano/boards/nano-matter/tutorials/user-manual/content.md
  content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/tutorials/user-manual/content.md
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/user-manual/content.md
  content/hardware/06.nicla/boards/nicla-vision/tutorials/user-manual/content.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/user-manual/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
Labels: enhancement, arduino

#1920 Declarations for new product release
  content/hardware/_unlisted/kits/opta-ext-d1608e/certifications/Arduino_AFX00005-DoC_CE.pdf
  content/hardware/_unlisted/kits/opta-ext-d1608e/certifications/Arduino_AFX00005-DoC_UKCA.pdf
  content/hardware/_unlisted/kits/opta-ext-d1608e/product.md
  content/hardware/_unlisted/kits/opta-ext-d1608s/certifications/Arduino_AFX00006-DoC_CE.pdf
  content/hardware/_unlisted/kits/opta-ext-d1608s/certifications/Arduino_AFX00006-DoC_UKCA.pdf
  content/hardware/_unlisted/kits/opta-ext-d1608s/product.md
Labels: arduino, certifications

#1960 Use standardized pin macros in Nano ESP32 "default" sketch
  content/hardware/03.nano/boards/nano-esp32/tutorials/cheat-sheet/cheat-sheet.md
Labels: enhancement, arduino, maker

#1931 [WIP] Workflow for Preview System
  .github/workflows/cloudflare.yml
  .github/workflows/preview.yml
  README.md
Labels: preview

#1915 [PC-1667] - Nicla Sense ME Datasheet Update
  content/hardware/06.nicla/boards/nicla-sense-me/datasheet/assets/niclaSenseMEBlockDiagram.png
  content/hardware/06.nicla/boards/nicla-sense-me/datasheet/assets/niclaSenseMEBlockDiagram.svg
  content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
Labels: documentation, Datasheet, fix/update, arduino, pro

#1965 Update getting-started.md
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/01.getting-started/getting-started.md
Labels: fix/update, community, education

#1973 Create Arduino_AKX00045-CERT_CE.pdf
  content/hardware/_unlisted/kits/science-kit-r3/certifications/Arduino_AKX00045-CERT_CE.pdf
Labels: arduino, certifications, preview

#1972 [MKC-1615]Update OTA article
  content/arduino-cloud/06.features/04.ota-getting-started/assets/OtA_board_selection.png
  content/arduino-cloud/06.features/04.ota-getting-started/assets/adding_variable.png
  content/arduino-cloud/06.features/04.ota-getting-started/assets/dashboard_widget.png
  content/arduino-cloud/06.features/04.ota-getting-started/assets/device_OtA.png
  content/arduino-cloud/06.features/04.ota-getting-started/assets/final_dashboard.png
  content/arduino-cloud/06.features/04.ota-getting-started/assets/iot_cloud_grid.png
  content/arduino-cloud/06.features/04.ota-getting-started/assets/select_device.png
  content/arduino-cloud/06.features/04.ota-getting-started/ota-getting-started.md
Labels: preview

#1974 Update content.md
  content/hardware/02.hero/boards/uno-rev3/tutorials/board-anatomy/content.md
Labels: bug, community, arduino, preview

#1979 small updates regarding the new Cloud Editor
  content/arduino-cloud/10.education/00.arduino-cloud-for-education/assets/download-sketch.png
  content/arduino-cloud/10.education/00.arduino-cloud-for-education/content.md
Labels: fix/update, education, cloud

#1983 updated Alvik DoCs to include 2 SKUs
  content/hardware/08.edu/solution-and-kits/alvik/certifications/Arduino_AKX00066-DoC_CE.pdf
  content/hardware/08.edu/solution-and-kits/alvik/certifications/Arduino_AKX00066-DoC_UKCA.pdf
Labels: arduino, certifications, preview

#1978 Update api-overview.md
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/api-overview/api-overview.md
Labels: fix/update, community, preview

#1986 Update User Manual [community]
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/user-manual/user-manual.md
Labels: documentation, community, education

#1985 Update libraries.md
  content/learn/01.starting-guide/04.software-libraries/libraries.md
Labels: documentation, Tutorial, arduino

#1988 New RoHS certs
  content/hardware/_unlisted/kits/opta-ext-d1608e/certifications/Arduino_AFX00005-CERT_RoHS.pdf
  content/hardware/_unlisted/kits/opta-ext-d1608e/product.md
  content/hardware/_unlisted/kits/opta-ext-d1608s/certifications/Arduino_AFX00005-CERT_RoHS.pdf
  content/hardware/_unlisted/kits/opta-ext-d1608s/product.md
Labels: arduino, certifications, preview
