Repository arduino/docs-content, pull requests merged in 2024-02, with the labels that each got.

#1718 [PC-1603] Docs 2.0 + Content Fixes - Nicla related changes
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/web-ble-dashboard/content.md
  content/hardware/06.nicla/boards/nicla-vision/product.md
  content/hardware/06.nicla/boards/nicla-vision/tutorials/user-manual/content.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/getting-started-ml/content.md
Labels: fix/update, arduino, pro

#1709 [Learn] Power Consumption (WIP)
  content/learn/04.electronics/11.power-consumption/assets/circuit.png
  content/learn/04.electronics/11.power-consumption/assets/consumption.png
  content/learn/04.electronics/11.power-consumption/assets/formula.png
  content/learn/04.electronics/11.power-consumption/assets/powerOutput.png
  content/learn/04.electronics/11.power-consumption/assets/startSampling.png
  content/learn/04.electronics/11.power-consumption/power-consumption.md
Labels: new, Tutorial, arduino

#1720 [PC-1568] Portenta Family Code Format Patch Docs
  content/hardware/04.pro/boards/portenta-h7/tutorials/secure-boot/secure-boot.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/03.uploading-sketches-m4/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/04.python-arduino-data-exchange/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/05.docker-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/06.waves-fleet-managment/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/07.custom-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/08.image-building/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/09.image-flashing/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/10.datalogging-iot/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/11.display-output-webgl/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/12.multi-protocol-gateway/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/13.wordpress-webserver/content.md
  content/hardware/04.pro/carriers/portenta-hat-carrier/tutorials/user-manual/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/x8-getting-started/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/tutorials/pmc-opta-temp-ctrl/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/tutorials/rtd-thermocouple-pmc/content.md
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/cli-tool/content.md
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/web-ble-dashboard/content.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/getting-started-ml/content.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/motion-detection-ml/content.md
  content/hardware/06.nicla/boards/nicla-voice/tutorials/user-manual/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/opta-azure-iot-tutorial-en/content.md
  content/software/plc-ide/tutorials/plc-ide-cloud-support/content.md
  content/software/plc-ide/tutorials/plc-ide-pin-mapping/content.md
  content/software/plc-ide/tutorials/plc-programming-introduction/content.md
Labels: documentation, Tutorial, pro

#1729 Product Family Anchor [WEDO-5326]
  content/hardware/01.mkr/family.md
  content/hardware/02.hero/family.md
  content/hardware/03.nano/family.md
  content/hardware/04.pro/family.md
  content/hardware/05.pro-solutions/family.md
  content/hardware/06.nicla/family.md
  content/hardware/07.opta/family.md
  content/hardware/10.mega/family.md
Labels: arduino, infrastructure

#1723 [GIGA Display Shield] Power Consumption Tests
  content/hardware/10.mega/shields/giga-display-shield/tutorials/01.getting-started/getting-started.md
Labels: fix/update, arduino, maker

#1724 [Nano ESP32] Add default sketch
  content/hardware/03.nano/boards/nano-esp32/tutorials/cheat-sheet/cheat-sheet.md
Labels: enhancement, arduino, maker

#1731 Add Power Consumption Article
  content/learn/04.electronics/11.power-consumption/assets/circuit.png
  content/learn/04.electronics/11.power-consumption/assets/consumption.png
  content/learn/04.electronics/11.power-consumption/assets/formula.png
  content/learn/04.electronics/11.power-consumption/assets/powerOutput.png
  content/learn/04.electronics/11.power-consumption/assets/startSampling.png
  content/learn/04.electronics/11.power-consumption/power-consumption.md
Labels: documentation, arduino, maker

#1695 updated name of uno r4 boards
  content/hardware/02.hero/boards/uno-r4-minima/datasheet/datasheet.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/adc-resolution/adc-resolution.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/can/can.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/debugger/debugger.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/eeprom/eeprom.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/rtc/rtc.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/usb-hid/usb-hid.md
  content/hardware/02.hero/boards/uno-r4-wifi/datasheet/datasheet.md
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/adc-resolution/adc-resolution.md
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/eeprom/eeprom.md
Labels: fix/update, arduino, maker

#1728 [MKC-1425] [MKC-1424] Add cloud to feature list
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/features.md
  content/hardware/02.hero/boards/uno-r4-wifi/features.md
  content/hardware/03.nano/boards/nano-33-iot/features.md
  content/hardware/03.nano/boards/nano-esp32/features.md
  content/hardware/03.nano/boards/nano-rp2040-connect/features.md
Labels: documentation, arduino

#1658 Fix computation of half wavelength in I2s-library-examples.md
  content/tutorials/generic/I2s-library-examples/I2s-library-examples.md
Labels: fix/update, community

#1747 Hannes7eicher/calibration docs fix
  content/built-in-examples/03.analog/Calibration/assets/circuit.png
Labels: documentation, fix/update, community, maker

#1742 [PC-1561] Nicla Sense ME Datasheet Update
  content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
Labels: documentation, pro

#1749 [Pc-1561] Jcarolinares/niclame datasheet hot fix
  content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
Labels: Datasheet, fix/update, arduino, pro

#1753 Fix broken links to Arduino IDE 2.x docs parent page
  content/software/ide-v2/tutorials/02.ide-v2-board-manager/ide-v2-board-manager.md
  content/software/ide-v2/tutorials/ide-v2-autocomplete-feature/ide-v2-autocomplete-feature.md
  content/software/ide-v2/tutorials/ide-v2-cloud-sketch-sync/ide-v2-cloud-sketch-sync.md
  content/software/ide-v2/tutorials/ide-v2-customize-auto-formatter/content.md
  content/software/ide-v2/tutorials/ide-v2-installing-a-library/ide-v2-installing-a-library.md
  content/software/ide-v2/tutorials/ide-v2-serial-monitor/ide-v2-serial-monitor.md
Labels: bug, arduino

#1755 [PC-1612] - Getting started with Arduino Cloud tutorial screenshots update
  content/software/plc-ide/tutorials/plc-ide-cloud-support/assets/iot-cloud-full-editor.png
Labels: fix/update, arduino, pro

#1757 Updating trademarks for PMC
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/features.md
Labels: fix/update, arduino, pro

#1759 [Nano ESP32] Serial Ports update
  content/hardware/03.nano/boards/nano-esp32/tutorials/cheat-sheet/cheat-sheet.md
Labels: fix/update, arduino, maker

#1764 New certificates for Nicla Vision
  content/hardware/06.nicla/boards/nicla-vision/certifications/Arduino_ABX00051-CERT_CE_RED.pdf
  content/hardware/06.nicla/boards/nicla-vision/certifications/Arduino_ABX00051-CERT_RCM.pdf
  content/hardware/06.nicla/boards/nicla-vision/certifications/Arduino_ABX00051-CERT_RoHS.pdf
  content/hardware/06.nicla/boards/nicla-vision/certifications/Arduino_ABX00051-CERT_UKCA.pdf
  content/hardware/06.nicla/boards/nicla-vision/product.md
Labels: arduino, certifications

#1771 removed markdown note from legacy docs
  content/retired/01.boards/arduino-101-619/content.md
  content/retired/01.boards/arduino-BT-v1/content.md
  content/retired/01.boards/arduino-BT/content.md
  content/retired/01.boards/arduino-diecimila/content.md
  content/retired/01.boards/arduino-duemilanove/content.md
  content/retired/01.boards/arduino-esplora/content.md
  content/retired/01.boards/arduino-ethernet-rev3-with-poe/content.md
  content/retired/01.boards/arduino-ethernet-rev3-without-poe/content.md
  content/retired/01.boards/arduino-fio/content.md
  content/retired/01.boards/arduino-gemma/content.md
  content/retired/01.boards/arduino-industrial-101/content.md
  content/retired/01.boards/arduino-isp/content.md
  content/retired/01.boards/arduino-leonardo-eth-2-with-poe/content.md
  content/retired/01.boards/arduino-leonardo-eth/content.md
  content/retired/01.boards/arduino-m0-pro/content.md
  content/retired/01.boards/arduino-m0/content.md
  content/retired/01.boards/arduino-mega-adk-rev3/content.md
  content/retired/01.boards/arduino-mini-05-without-header/content.md
  content/retired/01.boards/arduino-mini-05/content.md
  content/retired/01.boards/arduino-ng/content.md
  content/retired/01.boards/arduino-primo-core/content.md
  content/retired/01.boards/arduino-primo/content.md
  content/retired/01.boards/arduino-pro-mini/content.md
  content/retired/01.boards/arduino-pro/content.md
  content/retired/01.boards/arduino-serial-single-sided-3/content.md
  content/retired/01.boards/arduino-serial-single-sided/content.md
  content/retired/01.boards/arduino-serial/content.md
  content/retired/01.boards/arduino-tian/content.md
  content/retired/01.boards/arduino-tre/content.md
  content/retired/01.boards/arduino-uno-rev3-with-long-pins/content.md
  content/retired/01.boards/arduino-uno-wifi/content.md
  content/retired/01.boards/arduino-usb-2-serial-micro/content.md
  content/retired/01.boards/arduino-usb/content.md
  content/retired/01.boards/arduino-yun-mini/content.md
  content/retired/01.boards/arduino-yun-with-poe/content.md
  content/retired/01.boards/arduino-yun/content.md
  content/retired/01.boards/lilypad-arduino-main-board/content.md
  content/retired/01.boards/lilypad-arduino-simple/content.md
  content/retired/01.boards/lilypad-arduino-simplesnap/content.md
  content/retired/01.boards/lilypad-arduino-usb/content.md
  content/retired/02.shields/arduino-ethernet-shield-2-with-poe/content.md
  content/retired/02.shields/arduino-ethernet-shield-without-poe-module/content.md
  content/retired/02.shields/arduino-gsm-shield-2-antenna-connector/content.md
  content/retired/02.shields/arduino-gsm-shield-2-integrated-antenna/content.md
  content/retired/02.shields/arduino-gsm-shield/content.md
  content/retired/02.shields/arduino-lucky-shield/content.md
  content/retired/02.shields/arduino-usb-host-shield/content.md
  content/retired/02.shields/arduino-wifi-shield-101/content.md
  content/retired/02.shields/arduino-wifi-shield/content.md
  content/retired/02.shields/arduino-wireless-proto-shield/content.md
  content/retired/02.shields/arduino-wireless-sd-shield/content.md
  content/retired/02.shields/arduino-xbee-shield/content.md
  content/retired/02.shields/genuino-yun-shield/content.md
  content/retired/03.kits/arduino-basic-kit/content.md
  content/retired/03.kits/arduino-engineering-kit/content.md
  content/retired/03.kits/arduino-on-android-kit/content.md
  content/retired/03.kits/arduino-proto-extension-kit/content.md
  content/retired/03.kits/pro-gateway/content.md
  content/retired/03.kits/shield-mega-proto-kit-rev3/content.md
Labels: documentation, arduino

#1783 Nano 33 BLE Rev2 CAD Files
  content/hardware/03.nano/boards/nano-33-ble-rev2/downloads/ABX00071-cad-files.zip
Labels: documentation, fix/update, arduino, maker
