Repository arduino/docs-content, pull requests merged in 2024-09, with the labels that each got.

#2040 [PC-1607] - Portenta C33 I2S Interface Information Update (Datasheet and User Manual)
  content/hardware/04.pro/boards/portenta-c33/datasheets/datasheet.md
  content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/assets/portenta_c33_i2s_sine_wave.zip
  content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/content.md
Labels: documentation, enhancement, Datasheet, fix/update, pro, preview

#2111 [MKC-1749] Added cloud image widget information
  content/arduino-cloud/03.cloud-interface/03.dashboard-widgets/assets/widget-image.png
  content/arduino-cloud/03.cloud-interface/03.dashboard-widgets/dashboard-widgets.md
Labels: arduino, preview

#2148 [MKC-1814] Remove Overview from Learn Articles
  content/learn/01.starting-guide/00.getting-started-arduino/getting-started-arduino.md
  content/learn/05.communication/01.wire/wire.md
  content/learn/05.communication/08.bluetooth/bluetooth.md
  content/learn/05.communication/09.uart/uart.md
Labels: arduino, maker, preview

#2151 [PC-1828] Speech recognition tutorial check and revamp
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/speech-recognition-engine/content.md
Labels: preview

#2161 New compliance documentation
  package-lock.json
  package.json
  static/resources/cmrt/arduino-cmrt_1.docx
  static/resources/cmrt/arduino-cmrt_2.xlsx
  static/resources/psti/arduino-psti.pdf
Labels: preview

#2143 [MKC-1613] Update Postman Section
  content/arduino-cloud/07.api/02.arduino-iot-api/arduino-iot-api.md
  content/arduino-cloud/07.api/02.arduino-iot-api/assets/access-token.png
  content/arduino-cloud/07.api/02.arduino-iot-api/assets/auth-complete.png
  content/arduino-cloud/07.api/02.arduino-iot-api/assets/postman-1.png
  content/arduino-cloud/07.api/02.arduino-iot-api/assets/postman-2.png
  content/arduino-cloud/07.api/02.arduino-iot-api/assets/postman-3.png
Labels: preview

#2146 [MKC-1720] Update Compatible OTA Boards
  content/arduino-cloud/06.features/04.ota-getting-started/ota-getting-started.md
Labels: fix/update, preview

#2170 [PC-1956] Cloud for Business: Arduino Cloud CLI Docs Update
  content/arduino-cloud/09.business/09.arduino-cloud-for-business/content.md
Labels: fix/update, arduino, pro, preview

#2169 New compliance documentation for PLC Starter Kit
  content/hardware/_unlisted/kits/plc-starter-kit/certifications/Arduino_AKX00051-CERT_CE_EMC.pdf
  content/hardware/_unlisted/kits/plc-starter-kit/certifications/Arduino_AKX00051-CERT_CE_RED.pdf
  content/hardware/_unlisted/kits/plc-starter-kit/certifications/Arduino_AKX00051-CERT_UKCA.pdf
  content/hardware/_unlisted/kits/plc-starter-kit/certifications/Arduino_AKX00051-CERT_UKCA_RED.pdf
Labels: certifications

#2145 [MKC-1793] List of Arduino Cloud Compatible Boards
  content/arduino-cloud/02.hardware/01.devices/devices.md
  content/arduino-cloud/02.hardware/02.wifi/wifi.md
  content/arduino-cloud/02.hardware/03.lora/lora.md
  content/arduino-cloud/02.hardware/04.ethernet/ethernet.md
  content/arduino-cloud/02.hardware/05.cellular/cellular.md
Labels: arduino, preview

#2134 [MKC-1469] GIGA R1 WiFI Dual Core Debugging
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/breakpoint.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ide_elf.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ide_preferences.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ide_verbose.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/jtag_pins.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_debug_session_m4.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_debug_session_m7.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_elf_location.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_find-tab.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_find_window.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_optional_settings.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_select_core.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/assets/ozone_select_debugger.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-debugging/giga-debugging.md
Labels: documentation, Tutorial, arduino, how-to article, maker, preview

#2179 Corrected spelling
  content/learn/05.communication/01.wire/wire.md
Labels: fix/update, community

#2181 Update built-in-examples.md
  content/programming/03.built-in-examples/built-in-examples.md
Labels: bug, community

#2175 [MKC-1835] Add information on resistor
  content/built-in-examples/01.basics/Blink/Blink.md
Labels: fix/update

#2194 [MKC-1827] Revise cloud agent
  content/arduino-cloud/01.guides/00.overview/assets/editor.png
  content/arduino-cloud/02.hardware/00.cloud-agent/assets/install-agent.png
  content/arduino-cloud/02.hardware/00.cloud-agent/cloud-agent.md
Labels: fix/update, preview

#2190 [MKC-1832] MicroPython update examples with GIGA exception
  content/micropython/01.basics/05.digital-analog-pins/digital-analog-pins.md
Labels: documentation, preview
