Repository arduino/docs-content, pull requests merged in 2024-03, with the labels that each got.

#1774 [Nano ESP32] Added antenna specs
  content/hardware/03.nano/boards/nano-esp32/datasheet/assets/Nano_ESP32_Block_Diagram.png
  content/hardware/03.nano/boards/nano-esp32/datasheet/datasheet.md
Labels: documentation, arduino, maker

#1763 added mkr 485 shield guide
  content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/assets/MKR485_featured.jpg
  content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
Labels: Tutorial, arduino, maker

#1781 Correct minimum macOS version for Arduino IDE 2.x
  content/software/ide-v2/tutorials/getting-started/01.ide-v2-downloading-and-installing/ide-v2-downloading-and-installing.md
Labels: bug, arduino

#1738 [Arduino Cloud] Cloud Agent Mini-article
  content/arduino-cloud/02.hardware/00.cloud-agent/assets/board-connected.png
  content/arduino-cloud/02.hardware/00.cloud-agent/assets/install-agent.png
  content/arduino-cloud/02.hardware/00.cloud-agent/cloud-agent.md
Labels: arduino

#1792 Update Arduino IDE 2.x debugger tutorials for compatibility with versions >=2.3.0
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/atmel-ice/using-an-atmel-ice-with-the-ide-v2.md
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/mkr-jlink-setup/mkr-jlink.md
  content/hardware/02.hero/boards/zero/tutorials/debugging-with-zero/debugging-with-zero.md
Labels: bug, arduino

#1794 Updated image order [MKC-1494]
  content/learn/04.electronics/05.servo-motors/servo-motors.md
Labels: fix/update, arduino

#1793 Updated images in Built-in examples article
  content/built-in-examples/03.analog/AnalogInput/AnalogInput.md
Labels: fix/update, community, arduino

#1799 Updated SKU of product
  content/hardware/04.pro/carriers/portenta-breakout/tech-specs.yml
Labels: fix/update, arduino, pro

#1803 add warning note on Cloud template limitations
  content/arduino-cloud/10.education/02.templates/content.md
Labels: documentation, fix/update, education

#1808 Fixing the Classifying IMU Data sketch
  content/hardware/03.nano/boards/nano-33-ble-rev2/tutorials/get-started-with-machine-learning/get-started-with-machine-learning.md
Labels: fix/update, arduino

#1838 Add example for advanced cloud variable types in MicroPython
  content/arduino-cloud/01.guides/04.micropython/assets/colored-light-variable.png
  content/arduino-cloud/01.guides/04.micropython/assets/colored-light-widget.png
  content/arduino-cloud/01.guides/04.micropython/content.md
Labels: documentation, arduino

#1846 Nano Matter Core Section Moved
  content/hardware/03.nano/boards/nano-matter/tutorials/user-manual/content.md
Labels: documentation, pro, maker
