Repository arduino/docs-content, pull requests merged in 2024-12, with the labels that each got.

#2310 [PXCT-298] Opta: Datasheet Digital Input Specs Update
  content/hardware/07.opta/opta-family/opta-digital-exp/datasheet/datasheet.md
  content/hardware/07.opta/opta-family/opta-digital-exp/tech-specs.yml
  content/hardware/07.opta/opta-family/opta/datasheet/datasheet.md
  content/hardware/07.opta/opta-family/opta/tech-specs.yml
Labels: fix/update, arduino, pro

#2298 [PXCT-17] add RTC RPC example
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-dual-core/giga-dual-core.md
Labels: documentation, arduino, maker, preview

#2309 [PXCT-25] Updated I2C Table
  content/hardware/09.kits/maker/plug-and-make-kit/datasheet/datasheet.md
Labels: preview

#2323 Portenta X8: User Manual Arduino Linux Wizard Section Patch
  content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
Labels: fix/update, arduino, pro, preview

#2326 [PXCT-350] Maker naming conventions updated
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/product.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier-rev2/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/tutorials/mkr-iot-carrier-01-technical-reference/mkr-iot-carrier-01-technical-reference.md
  content/hardware/02.hero/boards/uno-r4-minima/features.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/02.hero/boards/uno-r4-wifi/features.md
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/03.nano/boards/nano-33-ble-rev2/tutorials/cheat-sheet/ble-cheat-sheet.md
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/essentials.md
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/tutorials/cheat-sheet/ble-cheat-sheet.md
  content/hardware/03.nano/boards/nano-33-ble-sense/essentials.md
  content/hardware/03.nano/boards/nano-33-ble-sense/tutorials/cheat-sheet/ble-cheat-sheet.md
  content/hardware/03.nano/boards/nano-esp32/suggestions.md
  content/hardware/03.nano/boards/nano-esp32/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/03.nano/boards/nano-rp2040-connect/essentials.md
  content/hardware/03.nano/boards/nano-rp2040-connect/tutorials/rp2040-01-technical-reference/rp2040-01-technical-reference.md
  content/hardware/10.mega/boards/giga-r1-wifi/features.md
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: preview

#2339 Nicla Voice: Glass Breaking Detection Application Note Requirements Update
  content/hardware/06.nicla/boards/nicla-voice/tutorials/glass-break-detector/content.md
Labels: fix/update, arduino, pro

#2337 [PXCT-409] Nano Matter Display Tutorial Update
  content/hardware/03.nano/boards/nano-matter/tutorials/02.getting-started-matter-display/getting-started-matter-display.md
Labels: preview

#2343 [pxct-418]add certifications
  content/hardware/08.edu/solution-and-kits/alvik/datasheet/datasheet.md
Labels: Datasheet, arduino, education
