Repository arduino/docs-content, pull requests merged in 2024-10, with the labels that each got.

#2109 MKC-1768 - Add multi-language information to API reference (ALVIK)
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/api-overview/api-overview.md
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/getting-started.md
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/setting-alvik-arduino-ide/assets/EsptoolSelection.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/setting-alvik-arduino-ide/assets/UploadWithProgrammer.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/setting-alvik-arduino-ide/assets/nano-esp32-gnd-b1.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/setting-alvik-arduino-ide/assets/uploadExample.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/setting-alvik-arduino-ide/image.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/setting-alvik-arduino-ide/setting-alvik-arduino-ide.md
Labels: documentation, education, preview

#2192 [PC-1958] Portenta X8: USB-C® to USB-A Requirement Update
  content/hardware/04.pro/boards/portenta-x8/tutorials/03.uploading-sketches-m4/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/04.python-arduino-data-exchange/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/05.docker-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/06.waves-fleet-managment/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/07.custom-container/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/08.image-building/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/09.image-flashing/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/10.datalogging-iot/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/11.display-output-webgl/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/12.multi-protocol-gateway/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/13.wordpress-webserver/content.md
  content/hardware/04.pro/carriers/portenta-breakout/tutorials/breakout-jlink-setup/breakout-jlink-setup.md
  content/hardware/04.pro/carriers/portenta-breakout/tutorials/getting-started/content.md
  content/hardware/04.pro/carriers/portenta-hat-carrier/tutorials/user-manual/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/catm1-and-nbiot/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/connecting-to-ttn/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/mpcie-4g-modem/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/user-manual/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/x8-getting-started/content.md
  content/hardware/04.pro/carriers/portenta-mid-carrier/tutorials/user-manual/content.md
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/tutorials/getting-started/getting-started.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/blob-detection/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/camera-to-bitmap-sd-card/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/connecting-to-ttn/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/creating-basic-face-filter/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/custom-machine-learning-model/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/ethernet-with-ide/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/ethernet-with-openmv/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/getting-started-camera/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/speech-recognition-engine/content.md
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/things-network-openmv/content.md
Labels: documentation, Tutorial, arduino, pro, preview

#2142 [PC-1929] Initial commit: Conveyor and sorting AppNote
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/ConveyorSortingSystem.zip
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung01.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung02.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung03.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung04.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung05.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung06.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung07.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung08.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung09.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung10.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung11.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/Rung12.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/arduino-ladder.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/arduino-plc-ide-new-program.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/arduino-plc-libraries.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/arduino-plc-sketch.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/button-wiring-1.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/conveyor-dashboard.gif
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/hardware-setting-2.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/opta-power-1.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/overview-1.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/photo-sensor-wiring.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/programmable-inputs.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/relay-outputs.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/relay-wiring-1.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/rgb-sensor-wiring-1.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/thumbnail.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/wiring-overview-1.png
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
Labels: pro, preview

#2196 [MKC-1795] Updated code on Lora MKR Wan 1310 LED Control Tutorial
  content/hardware/01.mkr/01.boards/mkr-wan-1310/tutorials/lora-button-press/lora-button-press.md
Labels: preview

#2184 [MKC-1854] GIGA CAN / ADC fixes
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-audio/content.md
Labels: documentation, fix/update, arduino, maker, preview

#2206 [PC-1952] - Opta Analog and Digital Expansions Product and Store Pages Name Alignment
  content/hardware/07.opta/opta-family/opta-analog-exp/features.md
  content/hardware/07.opta/opta-family/opta-analog-exp/product.md
  content/hardware/07.opta/opta-family/opta-digital-exp/features.md
  content/hardware/07.opta/opta-family/opta-digital-exp/product.md
Labels: fix/update, arduino, pro, preview

#2205 [PC-1957] Nicla Vision - Update Tutorial examples to work OpenMV
  content/hardware/06.nicla/boards/nicla-vision/tutorials/live-streaming/content.md
  content/hardware/06.nicla/boards/nicla-vision/tutorials/user-manual/content.md
Labels: preview

#2188 [PC-1961] Opta Digital Expansion - SSR Current Update
  content/hardware/07.opta/opta-family/opta-digital-exp/datasheet/datasheet.md
  content/hardware/07.opta/opta-family/opta-digital-exp/tech-specs.yml
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
Labels: fix/update, pro

#2136 [MKC-1771] Edit Dashboard IoT Remote App
  content/arduino-cloud/05.iot-remote-app/01.getting-started/assets/edit-dashbaord.png
  content/arduino-cloud/05.iot-remote-app/01.getting-started/iot-remote-app.md
Labels: documentation, arduino, maker, cloud, preview

#2210 [MKC-1828] Updated squareline tutorial
  content/hardware/10.mega/shields/giga-display-shield/tutorials/10.square-line-tutorial/assets/project_settings.png
  content/hardware/10.mega/shields/giga-display-shield/tutorials/10.square-line-tutorial/content.md
Labels: preview

#2216 [PC-1976] Edge Control Datasheet Bug Fix
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/Block_Diagram-EdgeControl_datasheet.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlAnalogSensors.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlConnectors_60.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlLCDscheme.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlLatchingOutputsJ10.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlLatchingOutputsJ9.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlLowPowerSensors.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlMountingHoles_60.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlOutline_60.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlPowerTree.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlPreview.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlSolidStateRelays.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlSolutionOverview.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControlWatermark.png
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControl_topology_bot_60.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/assets/edgeControl_topology_top_60.svg
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/datasheet.md
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/datasheet/rev2/datasheet.md
Labels: preview

#2126 2.0.19
  content/programming/02.libraries/libraries.md
  package-lock.json
  package.json
Labels: infrastructure

#2185 [MKC-1855] IMU tutorial Revised
  content/hardware/03.nano/boards/nano-33-ble-rev2/tutorials/imu-accelerometer/content.md
  content/hardware/03.nano/boards/nano-33-ble/tutorials/imu-accelerometer/content.md
Labels: preview

#2219 Update cheat-sheet.md
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: fix/update, community, maker

#2238 [HWU4M-87] Add instructions for ArduinoGraphics
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/led-matrix/led-matrix.md
Labels: fix/update, community, maker, preview

#2243 [MKC-1853] add 3d files resource
  content/hardware/08.edu/solution-and-kits/alvik/downloads/AKX00066-step.zip
Labels: arduino, education, preview

#2245 [MKC-1879] add note about battery decay
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/user-manual/user-manual.md
Labels: fix/update, arduino, education

#2224 [MKC-1629] Update SECRET Docs
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/add_secret_1.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/add_secret_2.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/add_secret_3.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/secret_feature_1.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/secret_feature_2.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_1.jpg
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_2.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_3.jpg
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_4.jpg
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_5.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_6.jpg
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_7.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_8.jpg
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/assets/share_secure_sketches_img_9.png
  content/arduino-cloud/04.cloud-editor/store-your-sensitive-data-safely-when-sharing/store-your-sensitive-data-safely-when-sharing.md
Labels: fix/update, arduino, maker, preview

#2203 [MKC-1693] Added reference to SYNC method on micropython
  content/arduino-cloud/01.guides/04.micropython/content.md
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-micropython/giga-micropython.md
Labels: documentation, preview

#2241 fix typo, it said sawtooth, it should say sine
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/dac/dac.md
Labels: fix/update, community, maker

#2252 Update LR links
  content/programming/01.language-reference/language-reference.md
Labels: preview

#2226 [MKC-1878] Shared sketches in IDE
  content/software/ide-v2/tutorials/ide-v2-shared-sketches/assets/account-settings.png
  content/software/ide-v2/tutorials/ide-v2-shared-sketches/assets/enter-id.png
  content/software/ide-v2/tutorials/ide-v2-shared-sketches/assets/open-preferences.png
  content/software/ide-v2/tutorials/ide-v2-shared-sketches/assets/shared-sketch.png
  content/software/ide-v2/tutorials/ide-v2-shared-sketches/ide-v2-shared-sketches.md
Labels: preview

#2254 [MNE-45] Add Nano ESP32 Version Info
  content/hardware/03.nano/boards/nano-esp32/features.md
  content/hardware/03.nano/boards/nano-esp32/tutorials/esp-now/esp-now.md
  content/hardware/03.nano/boards/nano-esp32/tutorials/getting-started-nano-esp32/getting-started-nano-esp32.md
Labels: documentation, arduino, maker, preview

#2215 [MKC-1924] Update iframe docs
  content/arduino-cloud/04.cloud-editor/embedding-create-iframes/assets/Embed_1.png
  content/arduino-cloud/04.cloud-editor/embedding-create-iframes/assets/Share_1.png
  content/arduino-cloud/04.cloud-editor/embedding-create-iframes/assets/iframe-highlight.png
  content/arduino-cloud/04.cloud-editor/embedding-create-iframes/embedding-create-iframes.md
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_gif_1.gif
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_gif_2.gif
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_1.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_2.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_3.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_4.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_5.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_6.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_7.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/assets/sharing_sketches_img_8.jpg
  content/arduino-cloud/04.cloud-editor/share-your-sketches/share-your-sketches.md
Labels: documentation, fix/update, arduino, maker, cloud, preview

#2248 [PXCT-66] Device Status Notification
  content/arduino-cloud/03.cloud-interface/04.triggers/triggers.md
  content/arduino-cloud/06.features/14.device-status/assets/shared-spaces.png
  content/arduino-cloud/06.features/14.device-status/device-status.md
Labels: documentation, preview

#2263 Pro 4G Module: Related Documentation Note Format Patch
  content/hardware/04.pro/carriers/portenta-max-carrier/tutorials/mpcie-4g-modem/content.md
  content/hardware/04.pro/carriers/portenta-mid-carrier/tutorials/user-manual/content.md
Labels: fix/update, Tutorial, arduino, pro, preview
