Repository arduino/docs-content, pull requests merged in 2024-11, with the labels that each got.

#2257 [PXCT-148]add updater info
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/assets/AlvikFirmwareUpdater30sec.gif
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/assets/online-lab-micropython.jpg
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/getting-started.md
Labels: fix/update, arduino, education

#2259 add info on online Micropython Lab
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/user-manual/user-manual.md
Labels: fix/update, arduino, education

#2273 [pxct-109] battery change steps
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/user-manual/user-manual.md
Labels: fix/update, arduino, education

#2287 [PXCT-100][PC-1972] Portenta H7: Pinout Documentation Update
  content/hardware/04.pro/boards/portenta-h7-lite-connected/interactive/ABX00042-pinout.png
  content/hardware/04.pro/boards/portenta-h7-lite/interactive/ABX00042-pinout.png
  content/hardware/04.pro/boards/portenta-h7/datasheet/assets/portentaH7_higDensity_pinOut.png
  content/hardware/04.pro/boards/portenta-h7/datasheet/assets/portentaH7_mkr_pinouts.png
  content/hardware/04.pro/boards/portenta-h7/datasheet/datasheet.md
  content/hardware/04.pro/boards/portenta-h7/downloads/ABX00042-full-pinout.pdf
  content/hardware/04.pro/boards/portenta-h7/interactive/ABX00042-pinout.png
Labels: fix/update, arduino, pro, preview

#2288 Replace non-breaking space characters in code snippets
  content/hardware/04.pro/boards/portenta-h7/tutorials/dual-core-processing/content.md
  content/learn/05.communication/06.one-wire/one-wire.md
Labels: bug, arduino

#2281 [PXCT-50] Update IoT Remote Update
  content/arduino-cloud/05.iot-remote-app/01.getting-started/assets/app-theme.png
  content/arduino-cloud/05.iot-remote-app/01.getting-started/assets/overview.png
  content/arduino-cloud/05.iot-remote-app/01.getting-started/assets/remote-app-activate-bkg-mode.png
  content/arduino-cloud/05.iot-remote-app/01.getting-started/assets/remote-app-setup.png
Labels: documentation, arduino, maker, cloud, preview

#2296 [PXCT-221] Conveyor Sorting App Note Gif Fix
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/conveyor-dashboard.gif
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/assets/dashboard.gif
  content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
Labels: pro, preview

#2294 [PXCT-212] Nicla Family: Enclosure STL Files Update
  content/hardware/06.nicla/boards/nicla-sense-me/downloads/ABX00050-stl.zip
  content/hardware/06.nicla/boards/nicla-vision/downloads/ABX00051-stl.zip
  content/hardware/06.nicla/boards/nicla-voice/downloads/ABX00061-stl.zip
Labels: documentation, fix/update, pro, preview

#2301 [PXCT-308] Opta: Expansion Firmware Documentation Update
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-process-multi.gif
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-process.gif
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-serial-2.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-serial-3.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-serial-4.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-serial-5.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update-serial.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/fw-update.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/library-install-2.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/assets/library-install.png
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
Labels: fix/update, arduino, pro, preview

#2304 [PXCT-320] Update GS Alvik - snippet improved
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/getting-started.md
Labels: preview
