Repository arduino/docs-content, pull requests merged in 2024-01, with the labels that each got.

#1008 Suggested libraries add `Aduino_PortentaBreakout`
  content/hardware/04.pro/carriers/portenta-breakout/essentials.md
Labels: Product page, fix/update, arduino, pro

#1062 Typo correction for the inclusion of the ArduinoBLE library.
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/enabling-ble/enabling-ble.md
Labels: community

#1118 Small typo/grammar suggestions
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/usb-hid/usb-hid.md
Labels: fix/update, arduino

#1319 Update cheat-sheet.md - fix: Table of IO pins
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/cheat-sheet/cheat-sheet.md
Labels: fix/update, community, maker

#1627 New certificates for various products
  content/hardware/01.mkr/01.boards/mkr-vidor-4000/certifications/Arduino_ABX00022-DoC_FCC.pdf
  content/hardware/01.mkr/01.boards/mkr-vidor-4000/product.md
  content/hardware/04.pro/boards/portenta-c33/certifications/Arduino_ABX00074-CERT_MIC.pdf
  content/hardware/04.pro/boards/portenta-c33/product.md
  content/hardware/04.pro/carriers/portenta-hat-carrier/certifications/Arduino_ASX00049-DoC_FCC.pdf
  content/hardware/07.opta/opta-family/opta/certifications/Arduino_AFX00002-CERT_CE_RED.pdf
  content/hardware/07.opta/opta-family/opta/certifications/Arduino_AFX00002-CERT_FCC_DSS.pdf
  content/hardware/07.opta/opta-family/opta/certifications/Arduino_AFX00002-CERT_FCC_DTS.pdf
Labels: arduino, certifications

#1645 Update cheat-sheet.md
  content/hardware/03.nano/boards/nano-esp32/tutorials/cheat-sheet/cheat-sheet.md
Labels: fix/update, community, maker

#1237 Updated bit-math.md
  content/learn/03.programming/11.bit-math/bit-math.md
Labels: fix/update, community

#1586 Update Servo Example
  content/learn/04.electronics/05.servo-motors/assets/capacitor.png
  content/learn/04.electronics/05.servo-motors/assets/servo_circuit_knob-pot.png
  content/learn/04.electronics/05.servo-motors/assets/servo_circuit_knob.png
  content/learn/04.electronics/05.servo-motors/assets/servo_circuit_sweep.png
  content/learn/04.electronics/05.servo-motors/servo-motors.md
Labels: fix/update, arduino, maker

#1650 Add missing prefixes to filenames of downloadables
  content/hardware/01.mkr/01.boards/mkr-gsm-1400/downloads/ABX00018-fritzing.fzpz
  content/hardware/01.mkr/03.carriers/mkr-connector-carrier/downloads/ASX00007-eagle-files.zip
  content/hardware/01.mkr/03.carriers/mkr-connector-carrier/downloads/ASX00007-schematics.pdf
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/downloads/ABX00047-schematics.pdf
  content/hardware/01.mkr/03.carriers/mkr-motor-carrier/downloads/ASX00003-eagle-files.zip
  content/hardware/01.mkr/03.carriers/mkr-motor-carrier/downloads/ASX00003-schematics.pdf
Labels: bug, arduino

#1652 [GIGA R1 WiFi] Update M4 compatibility
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-dual-core/giga-dual-core.md
Labels: arduino, maker

#1651 Renaming boards in tutorial for setup guide
  content/software/ide-v1/tutorials/getting-started/cores/arduino-avr/arduino-avr.md
Labels: fix/update, arduino

#1656 [PC-1544] Avnet Getting Started Kits Tutos | Nicla User Manuals add
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/user-manual/assets/compass.png
  content/hardware/06.nicla/boards/nicla-sense-me/tutorials/user-manual/content.md
  content/tutorials/generic/pro-edge-ai-ml-vision-speech-kit/pro-edge-ai-ml-vision-speech-kit.md
  content/tutorials/generic/pro-predictive-maintenance-kit/pro-predictive-maintenance-kit.md
Labels: arduino, pro

#1657 [PC-1544] Avnet Getting Started Tutorials Tables updates
  content/tutorials/generic/pro-edge-ai-ml-vision-speech-kit/pro-edge-ai-ml-vision-speech-kit.md
  content/tutorials/generic/pro-predictive-maintenance-kit/pro-predictive-maintenance-kit.md
Labels: arduino, pro

#1659 [UNO R4 WiFi] Datasheet update SRRC
  content/hardware/02.hero/boards/uno-r4-wifi/datasheet/datasheet.md
Labels: Datasheet, arduino, maker

#1544 [MicroPython] MicroPython reference (WIP)
  content/micropython/01.basics/08.reference/reference.md
Labels: documentation, arduino, maker

#1667 updated rotation of image
  content/hardware/02.hero/shields/9-axis-motion-shield/image.svg
Labels: fix/update, arduino, maker

#1560 Update secure-boot.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/secure-boot/secure-boot.md
Labels: fix/update, arduino, pro

#1674 Portenta Hat Carrier: SW Pinout Link Update
  content/hardware/04.pro/carriers/portenta-hat-carrier/downloads/ASX00049-full-pinout.pdf
  content/hardware/04.pro/carriers/portenta-hat-carrier/downloads/ASX00049-pinout-software-mapping.pdf
  content/hardware/04.pro/carriers/portenta-hat-carrier/product.md
Labels: Product page, fix/update, arduino, pro

#1676 Portenta Hat Carrier: SW Pinout File Placement w/ Docs 2.0 Update
  content/hardware/04.pro/carriers/portenta-hat-carrier/downloads/ASX00049-full-pinout.pdf
Labels: Product page, arduino, pro

#1677 Portenta Hat Carrier: SW Pinout Table In-Place Update
  content/hardware/04.pro/carriers/portenta-hat-carrier/downloads/ASX00049-full-pinout.pdf
Labels: Product page, arduino, pro

#1679 [PC-1540] PLC IDE: Documentation Trademarks Patch
  content/software/plc-ide/tutorials/can-setup/content.md
  content/software/plc-ide/tutorials/modbus-setup/content.md
  content/software/plc-ide/tutorials/plc-ide-cloud-support/content.md
  content/software/plc-ide/tutorials/plc-ide-pin-mapping/content.md
  content/software/plc-ide/tutorials/plc-ide-setup-license/content.md
  content/software/plc-ide/tutorials/plc-programming-introduction/content.md
Labels: documentation, Tutorial, arduino, pro

#1683 Wisgate lite 2 - Product page - Datasheet link fix
  content/hardware/05.pro-solutions/solutions-and-kits/wisgate-edge-lite-2/product.md
Labels: Product page, pro

#1686 updated product file name
  content/hardware/10.mega/boards/mega-2560/product.md
Labels: fix/update, arduino, maker

#1668 2.0.2
  content/micropython/01.basics/08.reference/py-hero-banner.png
  package-lock.json
  package.json
Labels: arduino, infrastructure

#1690 upload new certificate
  content/hardware/02.hero/boards/uno-r4-minima/certifications/Arduino_ABX00080-CERT_FCC.pdf
Labels: arduino, maker, certifications

#1688 added new tutorial to security hardware
  content/tutorials/security/security-consideration-hardware/assets/user-custom-code.png
  content/tutorials/security/security-consideration-hardware/security-consideration-hardware.md
Labels: documentation, Tutorial, arduino

#1689 Update cheat-sheet.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/cheat-sheet/cheat-sheet.md
Labels: fix/update, community, maker

#1681 Update shield-compatibility.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/shield-compatibility/shield-compatibility.md
Labels: fix/update, arduino, maker

#1692 Update cheat-sheet.md
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/cheat-sheet/cheat-sheet.md
Labels: documentation, fix/update, arduino

#1687 [GIGA R1 WiFi] Add NTP timezone example
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-wifi/giga-wifi.md
Labels: fix/update, arduino, maker

#1714 [GIGA R1 WiFi] Update RTC/NTP/UDP example.
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-wifi/giga-wifi.md
Labels: fix/update, arduino, maker

#1712 [PC-1604] Docs 2.0 + Content Fixes - Portenta related changes
  content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/ble-connectivity/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/creating-gui-with-lvgl/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/dual-core-processing/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/flash-optimized-key-value-store/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/getting-started-openmv-micropython/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/openmv-cheat-sheet/openmv-cheat-sheet.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/over-the-air-update/content.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/secure-boot/secure-boot.md
  content/hardware/04.pro/boards/portenta-h7/tutorials/setting-up-portenta/content.md
  content/hardware/04.pro/boards/portenta-x8/essentials.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/04.python-arduino-data-exchange/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/08.image-building/content.md
  content/hardware/04.pro/boards/portenta-x8/tutorials/12.multi-protocol-gateway/content.md
  content/hardware/04.pro/carriers/portenta-hat-carrier/tutorials/user-manual/content.md
  content/hardware/04.pro/carriers/portenta-max-carrier/essentials.md
  content/hardware/04.pro/shields/portenta-cat-m1-nb-iot-gnss-shield/tutorials/cheat-sheet/cheat-sheet.md
  content/hardware/04.pro/shields/portenta-vision-shield/essentials.md
  content/hardware/04.pro/shields/portenta-vision-shield/tech-specs.yml
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/speech-recognition-engine/content.md
Labels: fix/update, arduino, pro
