Repository arduino/docs-content, pull requests merged in 2024-07, with the labels that each got.

#2046 new certificate for Alvik & Nicla Voice
  content/hardware/06.nicla/boards/nicla-vision/certifications/Arduino_ABX00051-DoC_CE.pdf
  content/hardware/08.edu/solution-and-kits/alvik/certifications/Arduino_AKX00066-CERT_RoHS.pdf
  content/hardware/08.edu/solution-and-kits/alvik/product.md
Labels: certifications

#2056 Update arduino-reach.pdf
  static/resources/reach/arduino-reach.pdf
Labels: certifications

#2057 new certificates for Nicla Voice
  content/hardware/06.nicla/boards/nicla-voice/certifications/Arduino_ABX00061-CERT_IC.pdf
  content/hardware/06.nicla/boards/nicla-voice/certifications/Arduino_ABX00061-CERT_RCM.pdf
  content/hardware/06.nicla/boards/nicla-voice/product.md
Labels: certifications

#2054 new compliance documentation for Nicla Voice
  content/hardware/06.nicla/boards/nicla-voice/certifications/Arduino_ABX00061-CERT_FCC.pdf
  content/hardware/06.nicla/boards/nicla-voice/certifications/Arduino_ABX00061-DoC_FCC.pdf
  content/hardware/06.nicla/boards/nicla-voice/product.md
Labels: certifications

#2060 Declarations of conformity for Plug and Make Kit
  content/hardware/09.kits/maker/plug-and-make-kit/certifications/Arduino_AKX00069-DoC_CE.pdf
  content/hardware/09.kits/maker/plug-and-make-kit/certifications/Arduino_AKX00069-DoC_UKCA.pdf
Labels: certifications

#2065 [MKC-1746][MKC-1747] ZH Datasheets
  content/hardware/02.hero/boards/uno-rev3/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano-esp32/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano/datasheet/datasheet.md
  content/hardware/10.mega/boards/due/datasheet/datasheet.md
  content/hardware/10.mega/boards/mega-2560/datasheet/datasheet.md
Labels: preview

#2070 HTML codes for backlask especial escape character added to the path
  content/software/plc-ide/tutorials/plc-ide-setup-license/content.md
Labels: pro, preview

#2073 [PC-1863] - Opta Interrupt Pin Number Update
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
  content/hardware/07.opta/opta-family/opta/tutorials/04.getting-started-with-interrupts/content.md
Labels: fix/update, arduino, pro, preview

#2034 Fixes grammatical error. Removes multiple consecutive blank lines
  content/learn/03.programming/07.eeprom-guide/eeprom-guide.md
Labels: fix/update, community

#2078 [MKC-1751]Fix error in mkr wifi 1010 ds
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/datasheet/datasheet.md
Labels: bug, Datasheet, maker

#2079 [PC-1852] - Nano Matter Documentation Update (User Manual)
  content/hardware/03.nano/boards/nano-matter/tutorials/user-manual/content.md
Labels: documentation, fix/update, arduino, pro

#2043 [MKC-1267, HWGG-355] Add Webserial to Giga Camera Guide
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-camera/assets/connect_port.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-camera/assets/processing-example.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-camera/assets/video_filter.png
  content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-camera/giga-camera.md
Labels: documentation, enhancement, arduino, maker, preview

#2080 [PC-1782] - Opta Family Electrical Terminals Cable Size (Documentation)
  content/hardware/07.opta/opta-family/opta/datasheet/datasheet.md
  content/hardware/07.opta/opta-family/opta/downloads/AFX00001-AFX00002-AFX00003-datasheet.pdf
  content/hardware/07.opta/opta-family/opta/tech-specs.yml
  content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
Labels: documentation, Datasheet, Product page, arduino, pro, preview

#2088 [MKC-1750] Custom Cloud Templates Docs
  content/arduino-cloud/06.features/13.custom-templates/assets/ISDashboard.png
  content/arduino-cloud/06.features/13.custom-templates/assets/cloudinterfacetemplates.png
  content/arduino-cloud/06.features/13.custom-templates/assets/description.png
  content/arduino-cloud/06.features/13.custom-templates/assets/newtemplate.png
  content/arduino-cloud/06.features/13.custom-templates/assets/selectingThing.png
  content/arduino-cloud/06.features/13.custom-templates/content.md
Labels: cloud, preview

#2092 1412 - Incorrect circuit in Communication/ReadASCIIString example
  content/built-in-examples/04.communication/ReadASCIIString/ReadASCIIString.md
  content/built-in-examples/04.communication/ReadASCIIString/assets/circuit.png
Labels: fix/update, preview
