Repository arduino/docs-content, pull requests merged in 2025-09, with the labels that each got.

#2574 [PXCT-1221] Cloud - Updated information about network credentials
  content/arduino-cloud/01.guides/00.overview/overview.md
  content/arduino-cloud/01.guides/02.arduino-c/arduino-c.md
  content/arduino-cloud/01.guides/03.esp32/esp32.md
  content/arduino-cloud/01.guides/07.node-red/nodered-intro.md
  content/arduino-cloud/02.hardware/01.devices/devices.md
  content/arduino-cloud/03.cloud-interface/00.sketches/sketches.md
  content/arduino-cloud/03.cloud-interface/01.things/things.md
  content/arduino-cloud/06.features/02.cloud-scheduler/cloud-scheduler.md
  content/arduino-cloud/06.features/11.webhooks/iot-cloud-webhooks.md
  content/arduino-cloud/08.arduino-cloud-cli/07.getting-started/arduino-cloud-cli.md
  content/arduino-cloud/11.application-notes/cloud-relay-control/cloud-relay-control.md
  content/arduino-cloud/arduino-cloud/hardware/devices
Labels: preview

#2609 [PXCT-1266] Added Nano R4 in nano carriers/shields
  content/hardware/03.nano/carriers/nano-connector-carrier/compatibility.yml
  content/hardware/03.nano/carriers/nano-motor-carrier/compatibility.yml
  content/hardware/03.nano/carriers/nano-screw-terminal-adapter/compatibility.yml
  content/hardware/03.nano/carriers/nano-screw-terminal-adapter/tutorials/getting-started-nano-screw-terminal/getting-started-nano-screw-terminal.md
Labels: preview

#2610 [PXCT-1317] -Nano R4 Edge AI Application Note Update (Add Modulino Movement)
  content/hardware/03.nano/boards/nano-r4/tutorials/02.anomaly-detection-application-note/assets/hardware-setup-adxl335.png
  content/hardware/03.nano/boards/nano-r4/tutorials/02.anomaly-detection-application-note/assets/hardware-setup-modulino.png
  content/hardware/03.nano/boards/nano-r4/tutorials/02.anomaly-detection-application-note/assets/hardware-setup.png
  content/hardware/03.nano/boards/nano-r4/tutorials/02.anomaly-detection-application-note/assets/motor_anomaly_detection.zip
  content/hardware/03.nano/boards/nano-r4/tutorials/02.anomaly-detection-application-note/assets/motor_vibration_collector.zip
  content/hardware/03.nano/boards/nano-r4/tutorials/02.anomaly-detection-application-note/content.md
Labels: documentation, arduino, maker, preview

#2625 [PXCT-1274] - Portenta Vision Shield TTN Tutorial Update (Registering the Portenta on TTN)
  content/hardware/04.pro/shields/portenta-vision-shield/tutorials/connecting-to-ttn/content.md
Labels: documentation, fix/update, arduino, pro, preview

#2629 [PXCT-1359] Portenta Machine Control: User Manual Antenna Requirement Update
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/tutorials/user-manual/content.md
Labels: documentation, fix/update, arduino, pro, preview

#2556 [PXCT-1060] Added device provisioning documentation
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/attach-thing-to-bluetooth.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/connect-to-network-bluetooth.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/connect-with-bluetooth.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/connect-with-usb.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/connecting-with-usb-loading.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/creating-new-device.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/device-overview-usb.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/migration-process.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/network-config-device-page.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/selecting-board-migration.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/selecting-board-type.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/sketch-tab.png
  content/arduino-cloud/02.hardware/06.device-provisioning/assets/succesfull-connection-with-usb.png
  content/arduino-cloud/02.hardware/06.device-provisioning/content.md
Labels: preview

#2644 Create Arduino_ABX00063-CERT_RoHS.pdf
  content/hardware/10.mega/boards/giga-r1-wifi/certifications/Arduino_ABX00063-CERT_RoHS.pdf
Labels: certifications
