Repository arduino/docs-content, pull requests merged in 2025-05, with the labels that each got.

#2470 [PXCT-864] Replaced suggested library for Portenta C33
  content/hardware/04.pro/boards/portenta-c33/essentials.md
Labels: preview

#2477 [PXCT-865] Changed suggested libraries for Portanta H7 and H7 Lite Connected
  content/hardware/04.pro/boards/portenta-h7-lite-connected/essentials.md
  content/hardware/04.pro/boards/portenta-h7/essentials.md
Labels: preview

#2476 Updating link to cloud editor tutorial
  content/learn/01.starting-guide/03.the-arduino-web-editor/arduino-web-editor.md
Labels: bug, arduino, preview

#2482 [PXCT-924] Nano cheat sheet link fix
  content/hardware/03.nano/boards/nano-33-ble-sense-rev2/tutorials/cheat-sheet/ble-cheat-sheet.md
Labels: preview

#2485 Update ABX00042-pinout.png
  content/hardware/04.pro/boards/portenta-h7-lite-connected/interactive/ABX00042-pinout.png
Labels: bug, arduino, preview

#2490 removing RCM certificates
  content/hardware/01.mkr/01.boards/mkr-nb-1500/certifications/Arduino_ABX00019-CERT_RCM.pdf
  content/hardware/01.mkr/01.boards/mkr-nb-1500/product.md
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/certifications/Arduino_ABX00047-CERT_RCM.pdf
  content/hardware/01.mkr/03.carriers/mkr-iot-carrier/product.md
  content/hardware/02.hero/boards/uno-mini-limited-edition/certifications/Arduino_ABX00062-CERT_RCM.pdf
  content/hardware/02.hero/boards/uno-mini-limited-edition/product.md
  content/hardware/03.nano/boards/nano-33-ble-sense/certifications/Arduino_ABX00030_ABX00031_ABX00034_ABX00035-CERT_RCM.pdf
  content/hardware/03.nano/boards/nano-33-ble-sense/product.md
  content/hardware/03.nano/boards/nano-33-ble/certifications/Arduino_ABX00030_ABX00031_ABX00034_ABX00035-CERT_RCM.pdf
  content/hardware/03.nano/boards/nano-33-ble/product.md
  content/hardware/03.nano/boards/nano-rp2040-connect/certifications/Arduino_ABX00052_ABX00053-CERT_RCM.pdf
  content/hardware/03.nano/boards/nano-rp2040-connect/product.md
  content/hardware/03.nano/carriers/nano-screw-terminal-adapter/certifications/Arduino_ASX00037-CERT_RCM.pdf
  content/hardware/03.nano/carriers/nano-screw-terminal-adapter/product.md
  content/hardware/04.pro/boards/portenta-c33/certifications/Arduino_ABX00074-CERT_RCM.pdf
  content/hardware/04.pro/boards/portenta-c33/product.md
  content/hardware/04.pro/boards/portenta-h7-lite-connected/certifications/Arduino_ABX00046-CERT_RCM.pdf
  content/hardware/04.pro/boards/portenta-h7-lite-connected/product.md
  content/hardware/04.pro/boards/portenta-h7-lite/certifications/Arduino_ABX00045-CERT_RCM.pdf
  content/hardware/04.pro/boards/portenta-h7-lite/product.md
  content/hardware/04.pro/carriers/portenta-hat-carrier/certifications/Arduino_ASX00049-CERT_RCM.pdf
  content/hardware/04.pro/carriers/portenta-hat-carrier/product.md
  content/hardware/04.pro/shields/portenta-vision-shield/certifications/Arduino_ASX00021-CERT_RCM_Ethernet.pdf
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/certifications/Arduino_AKX00034-CERT_RCM.pdf
  content/hardware/05.pro-solutions/solutions-and-kits/edge-control/product.md
  content/hardware/06.nicla/boards/nicla-sense-me/certifications/Arduino_ABX00050-CERT_RCM.pdf
  content/hardware/06.nicla/boards/nicla-sense-me/product.md
  content/hardware/06.nicla/boards/nicla-voice/certifications/Arduino_ABX00061-CERT_RCM.pdf
  content/hardware/06.nicla/boards/nicla-voice/product.md
  content/hardware/_unlisted/kits/braccio++/certifications/Arduino_T050002-CERT_RCM.pdf
  content/hardware/_unlisted/kits/braccio++/product.md
  content/hardware/_unlisted/kits/explore-iot-kit/certifications/Arduino_AKX00027-CERT_RCM.pdf
  content/hardware/_unlisted/kits/explore-iot-kit/product.md
  content/hardware/_unlisted/kits/opla-iot-kit/certifications/Arduino_AKX00026-CERT_RCM.pdf
  content/hardware/_unlisted/kits/opla-iot-kit/product.md
Labels: arduino, certifications, preview

#2481 Updating Product Codes [PXCT-866]
  content/hardware/02.hero/boards/uno-r4-minima/product.md
  content/hardware/02.hero/boards/uno-rev3-smd/product.md
  content/hardware/03.nano/boards/nano-33-ble-rev2/product.md
  content/hardware/03.nano/boards/nano-esp32/product.md
  content/hardware/03.nano/boards/nano-matter/product.md
  content/hardware/04.pro/boards/portenta-c33/product.md
  content/hardware/04.pro/carriers/portenta-breakout/product.md
  content/hardware/06.nicla/boards/nicla-sense-env/product.md
  content/hardware/06.nicla/boards/nicla-voice/product.md
  content/hardware/08.edu/solution-and-kits/alvik/product.md
Labels: preview

#2493 [PXCT-966] UNO R4 WiFi Board Registration Steps
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/r4-wifi-getting-started/assets/animation.gif
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/r4-wifi-getting-started/r4-wifi-getting-started.md
Labels: preview

#2511 [PXCT-955] UNO R4 - Added missing section to minima HID tutorial
  content/hardware/02.hero/boards/uno-r4-minima/tutorials/usb-hid/usb-hid.md
Labels: preview

#2504 [Nano Connector Carrier] Added files for download
  content/hardware/03.nano/carriers/nano-connector-carrier/downloads/ASX00061-schematics.pdf
  content/hardware/03.nano/carriers/nano-connector-carrier/downloads/ASX00061-step-files.step
  content/hardware/03.nano/carriers/nano-connector-carrier/downloads/ASX00061-step.zip
Labels: preview

#2483 [PXCT-900] Changed battery connection image for mkr 1010 wifi
  content/hardware/01.mkr/01.boards/mkr-wifi-1010/tutorials/powering-with-batteries/assets/mkr_tutorial_01_img_01_rev2.png
Labels: preview
