Repository arduino/docs-content, pull requests merged in 2025-07, with the labels that each got.

#2557 [PXCT-1052] Add Modulino MicroPython library to essentials lists
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/essentials.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/essentials.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/essentials.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/essentials.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/essentials.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/essentials.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/essentials.md
Labels: preview

#2542 [PXCT-998] Cloud - Updated cloudlocation documentation
  content/arduino-cloud/03.cloud-interface/02.variables/variables.md
Labels: preview

#2536 [PXCT-1037] add certification to modulino datasheets
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/datasheet/datasheet.md
Labels: documentation, Datasheet, arduino, maker, preview

#2537 [PXCT-1019] add laser safety section - modulino distance
  content/hardware/11.accessories/modulino-nodes/modulino-distance/datasheet/assets/classOneLaserProduct.png
  content/hardware/11.accessories/modulino-nodes/modulino-distance/datasheet/datasheet.md
Labels: documentation, Datasheet, arduino, maker, preview

#2561 [PXCT-1099] Pins in the examples should be from 3.3V pin
  content/micropython/01.basics/00.digital-io/assets/pull-down.png
  content/micropython/01.basics/00.digital-io/assets/pull-up.png
  content/micropython/01.basics/01.analog-io/assets/photoresistor.png
Labels: preview

#2564 PFAS declaration upload
  content/productCertifications.md
  static/resources/pfas/arduino-pfas.pdf
Labels: certifications

#2568 [PXCT-1035] Arduino cloud - Updated shared cloud space article
  content/arduino-cloud/10.education/01.shared-spaces/assets/cloud-shared-spaces.png
  content/arduino-cloud/10.education/01.shared-spaces/content.md
Labels: preview

#2573 [PXCT-1084] Cloud - Updated status widget documentation
  content/arduino-cloud/03.cloud-interface/03.dashboard-widgets/dashboard-widgets.md
Labels: preview

#2582 [HWU4M-96[PXCT-929] add link to udev helpcenter article
  content/software/ide-v2/tutorials/getting-started/01.ide-v2-downloading-and-installing/ide-v2-downloading-and-installing.md
Labels: documentation, arduino, preview

#2585 [PXCT - 1036] - Nano R4 Datasheet Update (Power Data)
  content/hardware/03.nano/boards/nano-r4/datasheet/datasheet.md
Labels: documentation, Datasheet, fix/update, arduino, maker
