Repository arduino/docs-content, pull requests merged in 2025-08, with the labels that each got.

#2590 [PXCT-1138] Portenta Mid Carrier: SPI0_CS HD Pinout Update
  content/hardware/04.pro/carriers/portenta-mid-carrier/downloads/ASX00055-full-pinout.pdf
Labels: fix/update, arduino, pro

#2559 [PXCT-1073] Tutorial from library - Uno R4 Capacitor Tutorial
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/touch/assets/HoockupGuideExample.png
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/touch/assets/Touch_Cover_001.gif
  content/hardware/02.hero/boards/uno-r4-wifi/tutorials/touch/content.md
Labels: preview

#2589 [PXCT-1238] Modulino nodes (all) - Remove Nano classic and Nano Every
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/compatibility.yml
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/compatibility.yml
  content/hardware/11.accessories/modulino-nodes/modulino-distance/compatibility.yml
  content/hardware/11.accessories/modulino-nodes/modulino-knob/compatibility.yml
  content/hardware/11.accessories/modulino-nodes/modulino-movement/compatibility.yml
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/compatibility.yml
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/compatibility.yml
Labels: preview

#2601 [PXCT-1229] - Arduino Stella user manual update (examples)
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/assets/nearbydemo-serial-monitor.png
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/assets/nearbydemo-smartphone-app.png
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/assets/twr-portenta-serial.png
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/assets/twr-serial-plotter.gif
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/assets/twr-stella-serial.png
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/content.md
Labels: fix/update, arduino, pro, preview

#2599 [PXCT-1085] Cloud - Added link widget information
  content/arduino-cloud/03.cloud-interface/03.dashboard-widgets/assets/link-widget-options.png
  content/arduino-cloud/03.cloud-interface/03.dashboard-widgets/assets/link-widget.png
  content/arduino-cloud/03.cloud-interface/03.dashboard-widgets/dashboard-widgets.md
Labels: preview

#2603 NCC category and FCC DoC for Nano R4
  content/hardware/03.nano/boards/nano-r4/certifications/Arduino_ABX00142-DoC_FCC.pdf
  content/hardware/06.nicla/boards/nicla-sense-me/certifications/Arduino_ABX00050-CERT_NCC.pdf
  content/productCertifications.md
Labels: certifications, preview

#2604 [PXCT-1306] - Nano R4 Documentation Update (Add Suggested Libraries to Product Page)
  content/hardware/03.nano/boards/nano-r4/essentials.md
Labels: documentation, fix/update, arduino, maker, preview

#2605 [PXCT-1307] - UNO R4 Minima Documentation Update (Add Suggested Libraries to Product Page)
  content/hardware/02.hero/boards/uno-r4-minima/essentials.md
  content/hardware/03.nano/boards/nano-r4/essentials.md
Labels: documentation, fix/update, arduino, maker, preview

#2608 Suggested libraries fix (Nano R4 and UNO R4 Minima)
  content/hardware/02.hero/boards/uno-r4-minima/essentials.md
  content/hardware/03.nano/boards/nano-r4/essentials.md
Labels: fix/update, arduino, preview

#2607 [PXCT-1308] Portenta X8: Release Note Image 934 Update
  content/hardware/04.pro/boards/portenta-x8/tutorials/14.x8-firmware-release-notes/x8-firmware-release-notes.md
Labels: documentation, arduino, pro, preview
