Repository arduino/docs-content, pull requests merged in 2025-02, with the labels that each got.

#2359 2.0.26
  content/productCertifications.md
  package-lock.json
  package.json
Labels: preview

#2401 [PXCT-536] Nano Matter - Remove custom board url
  content/hardware/03.nano/boards/nano-matter/tutorials/01.user-manual/content.md
  content/hardware/03.nano/boards/nano-matter/tutorials/02.getting-started-matter-display/getting-started-matter-display.md
  content/hardware/03.nano/boards/nano-matter/tutorials/03.matter-fan/content.md
  content/hardware/03.nano/boards/nano-matter/tutorials/04.matter-relay-lightbulb/content.md
  content/hardware/03.nano/boards/nano-matter/tutorials/05.matter-rgb-light/content.md
  content/hardware/03.nano/boards/nano-matter/tutorials/06.matter-temp-sensor/content.md
Labels: documentation, fix/update, arduino, maker, preview

#2403 New certificates for Nano Matter
  content/hardware/03.nano/boards/nano-matter/certifications/Arduino_ABX00112-CERT_FCC.pdf
  content/hardware/03.nano/boards/nano-matter/certifications/Arduino_ABX00112-CERT_IC.pdf
  content/hardware/03.nano/boards/nano-matter/certifications/Arduino_ABX00112-CERT_RoHS.pdf
  content/hardware/03.nano/boards/nano-matter/product.md
Labels: certifications

#2411 Adding VCCI and SCIP to Product Compliance page
  content/hardware/06.nicla/boards/nicla-sense-env/certifications/Arduino_ABX00089-CERT_VCCI.pdf
  content/hardware/06.nicla/boards/nicla-sense-env/product.md
  content/productCertifications.md
  static/resources/scip/arduino-scip.pdf
Labels: certifications, preview

#2410 [PXCT-390] Updated cloud docs for device priority
  content/arduino-cloud/03.cloud-interface/00.sketches/sketches.md
Labels: preview

#2382 [PXCT-406] Added steps for package installer
  content/micropython/02.environment/03.modules/assets/package-installer.png
  content/micropython/02.environment/03.modules/assets/usb-comp.png
  content/micropython/02.environment/03.modules/modules.md
  content/micropython/05.modulinos/01.installation/assets/package-installer.png
  content/micropython/05.modulinos/01.installation/assets/usb-comp.png
  content/micropython/05.modulinos/01.installation/installation.md
Labels: preview

#2409 [PXCT-460] Added context for new UI (Online IDE)
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/assets/filemanageronline.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/assets/filesidebaronline.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/assets/onlinebuttons.png
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/getting-started/getting-started.md
  content/hardware/08.edu/solution-and-kits/alvik/tutorials/user-manual/user-manual.md
  content/micropython/02.environment/00.online-editor/assets/filemanageronline.png
  content/micropython/02.environment/00.online-editor/assets/filesidebaronline.png
  content/micropython/02.environment/00.online-editor/assets/onlinebuttons.png
  content/micropython/02.environment/00.online-editor/online-editor.md
Labels: preview

#2387 [PXCT-294] Added SPI info and wiring guide
  content/micropython/06.communication/spi/assets/spi.png
  content/micropython/06.communication/spi/spi.md
Labels: preview
