Repository arduino/docs-content, pull requests merged in 2025-04, with the labels that each got.

#2447 [PXCT-755] Added dates for X8 versions
  content/hardware/04.pro/boards/portenta-x8/tutorials/14.x8-firmware-release-notes/x8-firmware-release-notes.md
Labels: preview

#2449 2.0.30
  .github/workflows/preview.yml
  package-lock.json
  package.json
Labels: preview

#2452 [PXCT-667] Updated Uno R4 WiFi datasheet I2C information
  content/hardware/02.hero/boards/uno-r4-wifi/datasheet/datasheet.md
Labels: fix/update

#2451 2.0.31
  package-lock.json
  package.json
Labels: preview

#2460 [PXCT-831] Nicla Sense Me - Certification updates - Change Frequency band value
  content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
Labels: arduino, certifications
