Repository arduino/docs-content, pull requests merged in 2025-06, with the labels that each got.

#2523 2.0.38
  package-lock.json
  package.json
Labels: preview

#2534 [PXCT-1032] remove cloud plan feature minima
  content/hardware/02.hero/boards/uno-r4-minima/features.md
Labels: documentation, arduino, maker, preview

#2535 [PXCT-996] add forum slug - modulinos
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/product.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/product.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/product.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/product.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/product.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/product.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/product.md
Labels: documentation, enhancement, arduino, maker, preview

#2500 Modulino Nodes naming check
  content/hardware/03.nano/boards/nano-matter/tutorials/08.ml-magic-wand/content.md
  content/hardware/03.nano/carriers/nano-connector-carrier/datasheet/datasheet.md
  content/hardware/03.nano/carriers/nano-connector-carrier/tutorials/getting-started-nano-connector-carrier/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-proto-kit-me/datasheet/datasheet.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-proto-kit-me/features.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-proto-kit-ve/datasheet/datasheet.md
  content/hardware/05.pro-solutions/solutions-and-kits/portenta-proto-kit-ve/features.md
  content/hardware/09.kits/maker/plug-and-make-kit/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/tutorials/how-buttons-ardu/how-to-buttons-ardu.md
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/tutorials/how-buttons-mp/how-to-buttons-mp.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/tutorials/how-buzzer-ardu/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/tutorials/how-buzzer-mp/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/tutorials/how-distance-ardu/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/tutorials/how-distance-mp/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/tutorials/how-knob-ardu/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/tutorials/how-knob-mp/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/tutorials/how-movement-ardu/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/tutorials/how-movement-mp/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/tutorials/how-pixels-ardu/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/tutorials/how-pixels-mp/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/tutorials/how-thermo-ardu/content.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/tutorials/how-thermo-mp/content.md
  content/micropython/02.environment/03.modules/modules.md
  content/micropython/05.modulinos/01.installation/installation.md
  content/micropython/05.modulinos/modulinos.md
Labels: documentation, arduino

#2541 updated revision history
  content/hardware/11.accessories/modulino-nodes/modulino-buttons/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-buzzer/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-distance/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-knob/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-movement/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-pixels/datasheet/datasheet.md
  content/hardware/11.accessories/modulino-nodes/modulino-thermo/datasheet/datasheet.md
Labels: documentation, Datasheet, fix/update, arduino

#2547 UWB Shield & Stella: Post Update
  content/hardware/04.pro/shields/portenta-uwb-shield/tutorials/01.user-manual/content.md
  content/hardware/04.pro/shields/portenta-uwb-shield/tutorials/02.uwb-access-control-system/content.md
  content/hardware/05.pro-solutions/solutions-and-kits/stella/datasheet/datasheet.md
  content/hardware/05.pro-solutions/solutions-and-kits/stella/tutorials/01.user-manual/content.md
Labels: documentation, Tutorial, arduino, preview

#2533 [PXCT-956] Nano Classic Fixes
  content/hardware/03.nano/boards/nano/datasheet/assets/nano_power_tree.png
  content/hardware/03.nano/boards/nano/datasheet/datasheet.md
  content/hardware/03.nano/boards/nano/image.svg
Labels: documentation, Datasheet, arduino, maker, preview

#2530 [PXCT-969] add tiny-ml-kit step file
  content/hardware/_unlisted/kits/tiny-ml-kit/downloads/AKX00028-shield-step.zip
Labels: documentation, arduino, preview

#2548 9 Axis Motion Shield Tech Specs Update
  content/hardware/02.hero/shields/9-axis-motion-shield/tech-specs.yml
Labels: Product page, fix/update, arduino, maker

#2552 Update datasheet link in Getting Started [PXCT-1094]
  content/hardware/02.hero/shields/spe-shield/tutorials/getting-started/spe-getting-started.md
Labels: bug, arduino, preview

#2550 [PXCT-1071] UNO R4 - Fixed broken link to can tutorial
  content/learn/05.communication/10.can/can.md
Labels: preview
